(()=>{
let observer=null;
function esc(s=''){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function css(){if(document.getElementById('inlineAdminCss'))return;const s=document.createElement('style');s.id='inlineAdminCss';s.textContent=`
.inlineEditBtn{width:100%;margin:10px 0 0;border:1px solid #172033;background:#172033;color:#fff;border-radius:12px;padding:11px 14px;font-weight:900}.iaeOverlay{position:fixed;inset:0;background:#0008;z-index:1200;display:flex;align-items:flex-end;justify-content:center;padding:12px}.iaePanel{width:min(760px,100%);max-height:92vh;overflow:auto;background:#fff;border-radius:22px;padding:18px}.iaeTitle{font-size:20px;font-weight:900;margin-bottom:4px}.iaeSub{font-size:12px;color:#6f7786;margin-bottom:10px}.iaeLabel{display:block;font-size:12px;font-weight:900;color:#4b5563;margin:12px 0 4px}.iaeInput,.iaeText{width:100%;border:1px solid #dce3ec;border-radius:11px;padding:10px;font:inherit}.iaeText{min-height:82px;resize:vertical}.iaeChoice{border:1px solid #dce3ec;border-radius:13px;padding:10px;margin:8px 0}.iaeRow{display:flex;gap:8px;align-items:center}.iaeRow>*{flex:1}.iaeCheck{flex:0 0 auto;width:22px;height:22px}.iaeActions{display:flex;gap:8px;position:sticky;bottom:-18px;background:#fff;padding:12px 0 2px}.iaeBtn{flex:1;border:1px solid #dce3ec;background:#fff;border-radius:12px;padding:12px;font-weight:900}.iaeSave{background:#126fb3;color:#fff;border-color:#126fb3}.iaeMsg{font-size:12px;margin-top:8px}.iaeDanger{color:#d04444}.iaeOk{color:#0b8a60}
`;document.head.appendChild(s)}
async function isAdmin(){const sb=window.qbSupabase;if(!sb)return false;const {data:{user}}=await sb.auth.getUser();if(!user)return false;const {data}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();return data?.role==='admin'}
function currentQuestion(){try{return typeof pq==='function'?pq():null}catch{return null}}
async function fetchDbQuestion(q){const sb=window.qbSupabase;if(!sb||!q)return null;let {data,error}=await sb.from('questions').select('id,canonical_key,stem,instruction,explanation_overview,examiner_intent,exam_summary,medical_verification_note,updated_at,choices(id,choice_key,choice_text,is_correct,sort_order,explanation,correction_text,correct_for_other_context,examiner_distinction)').eq('canonical_key',q.id).maybeSingle();if(error)console.warn(error);return data||null}
function localChoiceKey(i){return String.fromCharCode(97+i)}
async function openEditor(){const q=currentQuestion();if(!q)return alert('現在の問題を取得できませんでした。');const dbq=await fetchDbQuestion(q);document.getElementById('iaeOverlay')?.remove();const o=document.createElement('div');o.id='iaeOverlay';o.className='iaeOverlay';const choices=(dbq?.choices?.length?dbq.choices.sort((a,b)=>a.sort_order-b.sort_order):q.choices.map((t,i)=>({choice_key:localChoiceKey(i),choice_text:t,is_correct:q.ans.includes(i),explanation:'',correction_text:'',correct_for_other_context:'',examiner_distinction:''})));
o.innerHTML=`<div class="iaePanel"><div class="iaeTitle">この問題を編集</div><div class="iaeSub">演習画面を離れずに編集できます。保存後はDB更新内容を現在の画面にも反映します。</div>${!dbq?'<div class="iaeMsg iaeDanger">この問題はまだSupabaseへ移行されていません。DB移行後はここから直接保存できます。現在は編集内容の確認のみ可能です。</div>':''}<label class="iaeLabel">問題文</label><textarea id="iaeStem" class="iaeText">${esc(dbq?.stem??q.q)}</textarea><label class="iaeLabel">問題全体の解説</label><textarea id="iaeOverview" class="iaeText">${esc(dbq?.explanation_overview??q.note??'')}</textarea><label class="iaeLabel">出題者の意図</label><textarea id="iaeIntent" class="iaeText">${esc(dbq?.examiner_intent??'')}</textarea><label class="iaeLabel">試験用まとめ</label><textarea id="iaeSummary" class="iaeText">${esc(dbq?.exam_summary??'')}</textarea><label class="iaeLabel">医学的検証メモ</label><textarea id="iaeVerify" class="iaeText">${esc(dbq?.medical_verification_note??'')}</textarea><label class="iaeLabel">各選択肢</label><div id="iaeChoices">${choices.map((c,i)=>`<div class="iaeChoice" data-i="${i}" data-id="${c.id||''}"><div class="iaeRow"><b style="flex:0 0 24px">${esc(c.choice_key)}</b><input class="iaeInput ctext" value="${esc(c.choice_text)}"><label style="flex:0 0 auto;font-size:12px;font-weight:900">正答 <input class="iaeCheck ccorrect" type="checkbox" ${c.is_correct?'checked':''}></label></div><textarea class="iaeText cexp" placeholder="なぜ○／×か">${esc(c.explanation||'')}</textarea><textarea class="iaeText ccorr" placeholder="×なら、どう直せば正しいか">${esc(c.correction_text||'')}</textarea><textarea class="iaeText calt" placeholder="別の疾患・病態なら正しい場合">${esc(c.correct_for_other_context||'')}</textarea><textarea class="iaeText cdist" placeholder="何と何を区別させたいか">${esc(c.examiner_distinction||'')}</textarea></div>`).join('')}</div><div id="iaeMsg" class="iaeMsg"></div><div class="iaeActions"><button id="iaeCancel" class="iaeBtn">閉じる</button><button id="iaeFull" class="iaeBtn">管理者ページ</button><button id="iaeSave" class="iaeBtn iaeSave" ${dbq?'':'disabled'}>保存</button></div></div>`;document.body.appendChild(o);o.querySelector('#iaeCancel').onclick=()=>o.remove();o.querySelector('#iaeFull').onclick=()=>location.href=`admin.html${dbq?`?question=${encodeURIComponent(dbq.id)}`:''}`;o.querySelector('#iaeSave').onclick=()=>saveEditor(q,dbq,o)}
async function saveEditor(localQ,dbq,o){if(!dbq)return;const sb=window.qbSupabase,msg=o.querySelector('#iaeMsg'),save=o.querySelector('#iaeSave');save.disabled=true;msg.className='iaeMsg';msg.textContent='保存中…';try{const payload={stem:o.querySelector('#iaeStem').value.trim(),explanation_overview:o.querySelector('#iaeOverview').value.trim()||null,examiner_intent:o.querySelector('#iaeIntent').value.trim()||null,exam_summary:o.querySelector('#iaeSummary').value.trim()||null,medical_verification_note:o.querySelector('#iaeVerify').value.trim()||null};const {data:{user}}=await sb.auth.getUser();if(user)payload.updated_by=user.id;let {error}=await sb.from('questions').update(payload).eq('id',dbq.id);if(error)throw error;const boxes=[...o.querySelectorAll('.iaeChoice')];for(let i=0;i<boxes.length;i++){const b=boxes[i],id=b.dataset.id,cp={choice_key:localChoiceKey(i),choice_text:b.querySelector('.ctext').value.trim(),is_correct:b.querySelector('.ccorrect').checked,sort_order:i,explanation:b.querySelector('.cexp').value.trim()||null,correction_text:b.querySelector('.ccorr').value.trim()||null,correct_for_other_context:b.querySelector('.calt').value.trim()||null,examiner_distinction:b.querySelector('.cdist').value.trim()||null};if(id){const r=await sb.from('choices').update(cp).eq('id',id);if(r.error)throw r.error}else{const r=await sb.from('choices').insert({...cp,question_id:dbq.id});if(r.error)throw r.error}}
localQ.q=payload.stem;localQ.note=payload.explanation_overview||'';localQ.choices=boxes.map(b=>b.querySelector('.ctext').value.trim());localQ.ans=boxes.map((b,i)=>b.querySelector('.ccorrect').checked?i:null).filter(i=>i!==null);msg.className='iaeMsg iaeOk';msg.textContent='保存しました。現在の問題画面にも反映しました。';setTimeout(()=>{o.remove();try{practice()}catch{}},650)}catch(e){msg.className='iaeMsg iaeDanger';msg.textContent=e.message||'保存に失敗しました。'}finally{save.disabled=false}}
async function inject(){if(!(await isAdmin()))return;const submit=document.getElementById('submit');if(!submit||document.getElementById('inlineEditBtn'))return;const b=document.createElement('button');b.id='inlineEditBtn';b.className='inlineEditBtn';b.textContent='✎ この問題を編集';b.onclick=openEditor;submit.insertAdjacentElement('afterend',b)}
function start(){css();observer=new MutationObserver(()=>inject());observer.observe(document.body,{childList:true,subtree:true});inject()}
document.addEventListener('DOMContentLoaded',start);
})();