(()=>{
const SUPABASE_URL='https://qebvqcubtyfgaakrzbzh.supabase.co';
const SUPABASE_KEY='sb_publishable_XdCnuTSA6bDh6vB04MlnPw_HDxJgVtZ';
let sb=null,currentUser=null,currentProfile=null;
function unlockQB(){document.documentElement.classList.remove('qb-auth-pending')}
function css(){const s=document.createElement('style');s.textContent=`.authOverlay{position:fixed;inset:0;background:#f5f7fb;z-index:1000;display:flex;align-items:center;justify-content:center;padding:18px}.authCard{width:min(440px,100%);background:#fff;border:1px solid #dce3ec;border-radius:22px;padding:20px}.authTitle{font-size:24px;font-weight:900;margin-bottom:6px}.authSub{font-size:13px;color:#6f7786;line-height:1.6;margin-bottom:14px}.authTabs,.acctRow{display:flex;gap:8px}.authTabs button{flex:1;border:1px solid #dce3ec;background:#fff;border-radius:12px;padding:10px;font-weight:800}.authTabs button.on{background:#126fb3;color:#fff}.authField{width:100%;border:1px solid #dce3ec;border-radius:12px;padding:12px;margin:6px 0;font-size:16px}.pwWrap{position:relative}.pwWrap .authField{padding-right:74px}.pwToggle{position:absolute;right:8px;top:50%;transform:translateY(-50%);border:0;background:transparent;color:#126fb3;font-weight:900;padding:8px;cursor:pointer}.authPrimary{width:100%;border:0;border-radius:13px;background:#126fb3;color:#fff;padding:13px;font-weight:900;margin-top:10px}.authMsg,.muted{font-size:12px;color:#6f7786}.acctBtn{margin-left:auto;display:flex;align-items:center;gap:8px;border:1px solid #dce3ec;background:#fff;border-radius:999px;padding:7px 12px 7px 8px;font-weight:800;cursor:pointer;white-space:nowrap}.acctAvatar{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#126fb3;color:#fff;font-size:13px;font-weight:900}.acctText{display:flex;flex-direction:column;align-items:flex-start;line-height:1.15}.acctStatus{font-size:10px;color:#6f7786;font-weight:700}.acctName{font-size:13px;color:#172033;font-weight:900}.acctSheet{position:fixed;inset:0;background:#0006;z-index:900;display:flex;align-items:flex-end;justify-content:center;padding:14px}.acctPanel{width:min(560px,100%);background:#fff;border-radius:20px;padding:18px}.acctRow>*{flex:1}.adminLink{display:block;text-align:center;margin-top:10px;padding:12px;border-radius:12px;background:#172033;color:#fff;text-decoration:none;font-weight:900}.gradeGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-top:14px}.gradeBtn{display:block;width:100%;min-height:92px;background:#fff;border:1px solid #dce3ec;border-radius:16px;padding:18px;text-align:left;font-size:20px;font-weight:900;box-shadow:0 2px 8px #1720330d;cursor:pointer}.gradeBtn .muted{display:block;margin-top:6px;font-size:12px;font-weight:700}@media(max-width:600px){.acctStatus{display:none}.acctBtn{padding-right:9px}.acctName{max-width:100px;overflow:hidden;text-overflow:ellipsis}.header{gap:6px}}`;document.head.appendChild(s)}
function el(h){const d=document.createElement('div');d.innerHTML=h.trim();return d.firstElementChild}function setBrand(){document.title='定期テスト対策QB';document.querySelectorAll('.brand').forEach(x=>x.textContent='定期テスト対策QB')}
function authOverlay(){let ov=document.getElementById('authOverlay');if(ov)return ov;ov=el(`<div id="authOverlay" class="authOverlay"><div class="authCard"><div class="authTitle">定期テスト対策QB</div><div class="authSub">ログインすると問題演習を開始できます。学習履歴・自己評価・メモはアカウントに保存されます。</div><div class="authTabs"><button id="tabLogin" class="on" type="button">ログイン</button><button id="tabSignup" type="button">新規登録</button></div><form id="authForm"><input id="displayName" class="authField" maxlength="30" placeholder="表示名（新規登録時）" style="display:none"><input id="email" class="authField" type="email" placeholder="メールアドレス" required><div class="pwWrap"><input id="password" class="authField" type="password" minlength="6" placeholder="パスワード" required><button id="pwToggle" class="pwToggle" type="button" aria-label="パスワードを表示">表示</button></div><button class="authPrimary" type="submit">ログイン</button><div id="authMsg" class="authMsg"></div></form></div></div>`);document.body.appendChild(ov);wireAuth(ov);return ov}
function wireAuth(ov){let mode='login';const login=ov.querySelector('#tabLogin'),signup=ov.querySelector('#tabSignup'),name=ov.querySelector('#displayName'),form=ov.querySelector('#authForm'),msg=ov.querySelector('#authMsg'),submit=form.querySelector('button[type="submit"]'),pw=ov.querySelector('#password'),toggle=ov.querySelector('#pwToggle');toggle.onclick=()=>{const show=pw.type==='password';pw.type=show?'text':'password';toggle.textContent=show?'隠す':'表示';toggle.setAttribute('aria-label',show?'パスワードを隠す':'パスワードを表示')};function setMode(m){mode=m;login.classList.toggle('on',m==='login');signup.classList.toggle('on',m==='signup');name.style.display=m==='signup'?'block':'none';name.required=m==='signup';submit.textContent=m==='signup'?'新規登録':'ログイン';msg.textContent=''}login.onclick=()=>setMode('login');signup.onclick=()=>setMode('signup');form.onsubmit=async e=>{e.preventDefault();msg.textContent='処理中…';const email=ov.querySelector('#email').value.trim(),password=pw.value;try{if(mode==='signup'){const display_name=name.value.trim();if(!display_name)throw Error('表示名を入力してください。');const {data,error}=await sb.auth.signUp({email,password,options:{data:{display_name}}});if(error)throw error;if(data.session){await onSession(data.session);ov.remove()}else msg.textContent='確認メールを送信しました。'}else{const {data,error}=await sb.auth.signInWithPassword({email,password});if(error)throw error;await onSession(data.session);ov.remove()}}catch(err){msg.textContent=err.message;msg.style.color='#d04444'}}}
async function loadProfile(){const {data,error}=await sb.from('profiles').select('id,display_name,role,grade_id').eq('id',currentUser.id).single();if(error){console.error('profile load failed',error);currentProfile={id:currentUser.id,display_name:currentUser.user_metadata?.display_name||'アカウント',role:'user'};return currentProfile}currentProfile=data;return data}
function accountLabel(){return currentProfile?.display_name||currentUser?.email?.split('@')[0]||'アカウント'}
function accountInitial(){return [...accountLabel()][0]||'U'}
function addAccountButton(){const h=document.querySelector('.header');if(!h)return;let b=document.getElementById('acctBtn');if(!b){b=document.createElement('button');b.id='acctBtn';b.className='acctBtn';b.type='button';b.onclick=accountSheet;h.appendChild(b)}b.innerHTML=`<span class="acctAvatar">${accountInitial()}</span><span class="acctText"><span class="acctStatus">ログイン中</span><span class="acctName">${accountLabel()}</span></span>`}
function accountSheet(){document.getElementById('acctSheet')?.remove();const s=el(`<div id="acctSheet" class="acctSheet"><div class="acctPanel"><div class="authTitle">アカウント</div><div class="authSub">ログイン中：${currentUser?.email||''}</div><label class="muted">表示名</label><div class="acctRow"><input id="acctName" class="authField" maxlength="30" value="${(currentProfile?.display_name||'').replace(/"/g,'&quot;')}"><button id="saveName" class="authPrimary">保存</button></div>${currentProfile?.role==='admin'?'<a class="adminLink" href="./admin.html">管理者ページ</a>':''}<button id="logoutBtn" class="authPrimary" style="background:#fff;color:#d04444;border:1px solid #dce3ec">ログアウト</button><button id="closeAcct" class="authPrimary" style="background:#fff;color:#172033;border:1px solid #dce3ec">閉じる</button></div></div>`);document.body.appendChild(s);s.querySelector('#closeAcct').onclick=()=>s.remove();s.querySelector('#logoutBtn').onclick=async()=>{await sb.auth.signOut();location.reload()};s.querySelector('#saveName').onclick=async()=>{const v=s.querySelector('#acctName').value.trim();if(!v)return;const {error}=await sb.from('profiles').update({display_name:v}).eq('id',currentUser.id);if(error)return alert(error.message);currentProfile.display_name=v;addAccountButton();s.remove()}}
function openM4(){if(typeof window.qbOpenSubjects==='function'){window.qbOpenSubjects();return}try{if(typeof state!=='undefined'&&typeof subjects==='function'){state.screen='subjects';if(typeof save==='function')save();subjects();const C=document.getElementById('crumb'),H=document.getElementById('home');if(C)C.textContent='M4 ＞ 科目を選択';if(H){H.classList.remove('hidden');H.textContent='学年一覧';H.onclick=showGradeScreen}return}}catch(e){console.error('M4 navigation failed',e)}window.location.href='./index.html#subjects'}
function showGradeScreen(){const V=document.getElementById('view'),C=document.getElementById('crumb'),H=document.getElementById('home');if(!V)return;if(C)C.textContent='学年を選択';H?.classList.add('hidden');V.innerHTML=`<div class="card"><div class="title">学年一覧</div><div class="sub">学年を選んでください。</div></div><div class="gradeGrid"><button id="gradeM4" class="gradeBtn" type="button"><span>M4</span><span class="muted">現在利用可能</span></button></div>`;document.getElementById('gradeM4').onclick=openM4}
window.showGradeScreen=showGradeScreen;window.openM4Subjects=openM4;
async function onSession(session){currentUser=session?.user||null;if(!currentUser)return;await loadProfile();setBrand();addAccountButton();unlockQB();if(!location.pathname.endsWith('/admin.html'))setTimeout(showGradeScreen,0)}
async function init(){css();setBrand();if(!window.supabase){console.error('Supabase client library is not loaded');authOverlay();return}sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);window.qbSupabase=sb;const {data}=await sb.auth.getSession();if(data.session)await onSession(data.session);else authOverlay();sb.auth.onAuthStateChange(async(_e,session)=>{if(session&&!currentUser){await onSession(session);document.getElementById('authOverlay')?.remove()}if(!session&&currentUser)location.reload()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();