(()=>{
'use strict';
const SUBJECT_SLUG='wakan';
const STORE='m4_qb_v7';
const LOCAL_CACHE='m4_qb_cache_v1';
let sb=null,user=null,subject=null,questions=[],units=[];
let state={screen:'subjects',unitId:null,selected:[],practice:[],pi:0,filters:[],history:{},ratings:{},qstate:{},sessionId:null,mode:'ordered'};
let sel=new Set(),submitted=false,reviewOnly=false;
const V=document.getElementById('view'),C=document.getElementById('crumb'),H=document.getElementById('home'),M=document.getElementById('modal');
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(s){if(!s)return '';const d=new Date(s);return `${d.getFullYear()}/${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function saveLocal(){try{localStorage.setItem(STORE,JSON.stringify({...state,history:undefined,ratings:undefined,qstate:undefined}));localStorage.setItem(LOCAL_CACHE,JSON.stringify({questions,units,at:new Date().toISOString()}))}catch(e){}}
function loadLocalState(){try{const x=JSON.parse(localStorage.getItem(STORE)||'null');if(x)state={...state,...x,history:{},ratings:{},qstate:{}}}catch(e){}}
async function waitForSupabase(){for(let i=0;i<100;i++){if(window.qbSupabase){sb=window.qbSupabase;const r=await sb.auth.getUser();if(r.data?.user){user=r.data.user;return true}}await new Promise(r=>setTimeout(r,100))}return false}
function mapQuestion(r){const occ=[...(r.question_occurrences||[])].sort((a,b)=>(b.academic_year||0)-(a.academic_year||0));const primary=occ[0]||{};const ch=[...(r.choices||[])].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));return {
 id:r.canonical_key||r.id,dbId:r.id,canonicalKey:r.canonical_key||r.id,q:r.stem,instruction:r.instruction||'',unit:r.units?.slug||'uncategorized',unitName:r.units?.name||'未分類・分類不明',subtopic:r.subtopics?.name||'その他',subtopicId:r.subtopic_id||null,studyOrder:r.study_order||0,answerMode:r.answer_mode||'multiple',choices:ch.map(x=>x.choice_text),choiceKeys:ch.map(x=>x.choice_key),ans:ch.map((x,i)=>x.is_correct?i:null).filter(i=>i!==null),choiceDetails:ch,note:r.explanation_overview||'',examinerIntent:r.examiner_intent||'',examSummary:r.exam_summary||'',medicalVerificationNote:r.medical_verification_note||'',year:occ.length?occ.map(x=>x.academic_year).filter(Boolean).join('・'):'年度不明',exam:primary.exam_type||'',qnum:primary.original_question_number||'',occurrenceId:primary.id||null,occurrences:occ
 }}
async function loadCatalog(){const s=await sb.from('subjects').select('id,slug,name,grade_id').eq('slug',SUBJECT_SLUG).single();if(s.error)throw s.error;subject=s.data;const uq=await sb.from('units').select('id,slug,name,sort_order').eq('subject_id',subject.id).eq('is_active',true).order('sort_order');if(uq.error)throw uq.error;units=[{id:'__all__',slug:'__all__',name:'すべて（収録済み）',sort_order:-1},...(uq.data||[])];const q=await sb.from('questions').select('id,canonical_key,stem,instruction,answer_mode,study_order,subtopic_id,explanation_overview,examiner_intent,exam_summary,medical_verification_note,units(id,slug,name),subtopics(id,slug,name),choices(id,choice_key,choice_text,is_correct,sort_order,explanation,correction_text,correct_for_other_context,examiner_distinction),question_occurrences(id,academic_year,exam_type,original_question_number,source_page,source_file,official_answer,answer_source)').eq('subject_id',subject.id).eq('status','published').order('study_order');if(q.error)throw q.error;questions=(q.data||[]).map(mapQuestion);window.QB_QUESTIONS=questions;window.QB_DB_READY=true}
async function loadUserData(){const [a,r,qs]=await Promise.all([
 sb.from('attempts').select('question_id,is_correct,answered_at').eq('user_id',user.id).order('answered_at',{ascending:false}),
 sb.from('question_ratings').select('question_id,rating').eq('user_id',user.id),
 sb.from('user_question_state').select('question_id,has_viewed_explanation,explanation_viewed_at,has_answered,last_answered_at,last_is_correct,last_selected_choice_keys,updated_at').eq('user_id',user.id)
]);
 if(a.error)console.warn(a.error);if(r.error)console.warn(r.error);if(qs.error)console.warn(qs.error);
 const byDb=new Map(questions.map(q=>[q.dbId,q.id]));state.history={};(a.data||[]).forEach(x=>{const id=byDb.get(x.question_id);if(!id)return;(state.history[id]||(state.history[id]=[])).push({correct:x.is_correct,at:x.answered_at});state.history[id]=state.history[id].slice(0,3)});state.ratings={};(r.data||[]).forEach(x=>{const id=byDb.get(x.question_id);if(id)state.ratings[id]=x.rating});state.qstate={};(qs.data||[]).forEach(x=>{const id=byDb.get(x.question_id);if(id)state.qstate[id]=x});
}
const hist=id=>state.history[id]||[];const rating=id=>state.ratings[id]||'';const qstatus=id=>state.qstate[id]||{};
function hhtml(id){const a=hist(id);if(!a.length)return '<span class="h">未解答</span>';return a.map((x,i)=>`<span class="h ${x.correct?'ok':'bad'}">${i===0?'前回':(i+1)+'回前'} ${x.correct?'○':'×'} ${fmt(x.at)}</span>`).join('')}
function qset(){return questions.filter(q=>state.unitId==='__all__'||q.unit===state.unitId)}
function passFilter(q){if(!state.filters.length)return true;return state.filters.some(f=>{if(f==='未演習')return !qstatus(q.id).has_answered;if(f==='解説のみ')return qstatus(q.id).has_viewed_explanation&&!qstatus(q.id).has_answered;return rating(q.id)===f})}
async function setRating(q,v){state.ratings[q.id]=v;await sb.from('question_ratings').upsert({user_id:user.id,question_id:q.dbId,rating:v,updated_at:new Date().toISOString()},{onConflict:'user_id,question_id'});saveLocal()}
async function recordAnswer(q,ok){const now=new Date().toISOString(),keys=[...sel].sort((a,b)=>a-b).map(i=>q.choiceKeys[i]||String.fromCharCode(97+i));const r=await sb.from('attempts').insert({user_id:user.id,question_id:q.dbId,occurrence_id:q.occurrenceId,selected_choice_keys:keys,is_correct:ok,answered_at:now});if(r.error)throw r.error;state.history[q.id]=[{correct:ok,at:now},...hist(q.id)].slice(0,3);const payload={user_id:user.id,question_id:q.dbId,has_viewed_explanation:true,explanation_viewed_at:now,has_answered:true,last_answered_at:now,last_is_correct:ok,last_selected_choice_keys:keys,updated_at:now};const s=await sb.from('user_question_state').upsert(payload,{onConflict:'user_id,question_id'});if(s.error)throw s.error;state.qstate[q.id]=payload}
async function recordReview(q){const now=new Date().toISOString();const old=qstatus(q.id);const payload={user_id:user.id,question_id:q.dbId,has_viewed_explanation:true,explanation_viewed_at:now,has_answered:!!old.has_answered,last_answered_at:old.last_answered_at||null,last_is_correct:typeof old.last_is_correct==='boolean'?old.last_is_correct:null,last_selected_choice_keys:old.last_selected_choice_keys||[],updated_at:now};const s=await sb.from('user_question_state').upsert(payload,{onConflict:'user_id,question_id'});if(s.error)throw s.error;state.qstate[q.id]=payload}
async function saveSession(completed=false){if(!state.practice.length||!subject)return;const ids=state.practice.map(id=>questions.find(q=>q.id===id)?.dbId).filter(Boolean);const unit=units.find(u=>u.slug===state.unitId);const payload={user_id:user.id,subject_id:subject.id,unit_id:unit&&unit.id!=='__all__'?unit.id:null,mode:state.mode||'ordered',question_ids:ids,current_index:state.pi,is_completed:completed,last_active_at:new Date().toISOString(),metadata:{canonical_keys:state.practice,unit_slug:state.unitId}};if(completed)payload.completed_at=new Date().toISOString();if(state.sessionId){const r=await sb.from('practice_sessions').update(payload).eq('id',state.sessionId);if(r.error)console.warn(r.error)}else{const r=await sb.from('practice_sessions').insert(payload).select('id').single();if(r.error)console.warn(r.error);else state.sessionId=r.data.id}saveLocal()}
async function findResume(){const r=await sb.from('practice_sessions').select('id,unit_id,mode,question_ids,current_index,last_active_at,metadata').eq('user_id',user.id).eq('subject_id',subject.id).eq('is_completed',false).order('last_active_at',{ascending:false}).limit(1).maybeSingle();if(r.error||!r.data)return;const s=r.data,keys=Array.isArray(s.metadata?.canonical_keys)?s.metadata.canonical_keys:[];if(!keys.length)return;showResume(s,keys)}
function showResume(s,keys){document.getElementById('qbResumeSheet')?.remove();const d=document.createElement('div');d.id='qbResumeSheet';d.innerHTML=`<div class="resumeBox"><div><div class="meta">${fmt(s.last_active_at)}</div><b>続きから解く</b><div class="meta">${Math.min((s.current_index||0)+1,keys.length)}/${keys.length}問目</div></div><div class="resumeBtns"><button id="resumeClose" class="btn">×</button><button id="resumeGo" class="primary small">▶</button></div></div>`;document.body.appendChild(d);d.querySelector('#resumeClose').onclick=()=>d.remove();d.querySelector('#resumeGo').onclick=()=>{state.practice=keys.filter(id=>questions.some(q=>q.id===id));state.pi=Math.min(s.current_index||0,Math.max(state.practice.length-1,0));state.unitId=s.metadata?.unit_slug||'__all__';state.mode=s.mode||'ordered';state.sessionId=s.id;submitted=false;reviewOnly=false;sel=new Set();d.remove();go('practice')}}
function go(screen){state.screen=screen;saveLocal();render();scrollTo({top:0,behavior:'smooth'})}
function render(){H.classList.toggle('hidden',state.screen==='subjects'||state.screen==='practice');if(state.screen==='subjects')subjects();else if(state.screen==='units')unitList();else if(state.screen==='problems')problems();else practice()}
function subjects(){C.textContent='M4 ＞ 科目を選択';V.innerHTML=`<div class="card"><div class="title">科目一覧</div><div class="sub">勉強する科目を選んでください。</div></div><button id="wakan" class="list"><div><div class="lt">和漢医学概論</div><div class="meta">Supabase収録 ${questions.length}問</div></div><div>›</div></button>`;document.getElementById('wakan').onclick=()=>go('units')}
function unitList(){C.textContent='和漢医学概論 ＞ 単元';V.innerHTML=`<div class="card"><div class="title">和漢医学概論</div><div class="sub">Supabaseの正式データを表示しています。</div></div>`+units.map(u=>{const q=questions.filter(x=>u.slug==='__all__'||x.unit===u.slug),answered=q.filter(x=>qstatus(x.id).has_answered).length,reviewed=q.filter(x=>qstatus(x.id).has_viewed_explanation).length;return `<button class="list" data-u="${esc(u.slug)}"><div style="flex:1"><div class="lt">${esc(u.name)}</div><div class="meta">${q.length}問・解答済み ${answered}/${q.length}・解説確認済み ${reviewed}/${q.length}</div><div class="progress"><div style="width:${q.length?answered/q.length*100:0}%"></div></div></div><div>›</div></button>`}).join('');V.querySelectorAll('[data-u]').forEach(b=>b.onclick=()=>{state.unitId=b.dataset.u;state.filters=[];state.selected=qset().map(q=>q.id);go('problems')})}
function problems(){const all=qset(),q=all.filter(passFilter);state.selected=state.selected.filter(id=>q.some(x=>x.id===id));if(!state.selected.length&&q.length)state.selected=q.map(x=>x.id);const subs=[...new Set(q.map(x=>x.subtopic))],u=units.find(x=>x.slug===state.unitId),name=u?.name||'';C.textContent=`和漢医学概論 ＞ ${name} ＞ 問題一覧`;let s=`<div class="card"><div class="title">${esc(name)}</div><div class="filters">${['◎','○','△','×','-','未演習','解説のみ'].map(v=>`<button class="filter ${state.filters.includes(v)?'on':''}" data-f="${v}">${v}</button>`).join('')}</div><div class="meta">表示 ${q.length}/${all.length}問</div></div><div class="card"><div class="row"><b>範囲選択</b><button id="all" class="btn">${state.selected.length===q.length&&q.length?'すべて解除':'すべて選択'}</button></div>`;subs.forEach(st=>{const z=q.filter(x=>x.subtopic===st),ck=z.length&&z.every(x=>state.selected.includes(x.id));s+=`<label class="range"><input type="checkbox" data-st="${esc(st)}" ${ck?'checked':''}><div><b>${esc(st)}</b><div class="meta">${z.length}問</div></div></label>`});s+='</div><div class="card"><b>問題一覧（'+q.length+'問）</b>';q.forEach((x,i)=>{const st=qstatus(x.id),status=st.has_answered?(st.last_is_correct?'正解':'不正解'):st.has_viewed_explanation?'解説のみ':'未閲覧';s+=`<div class="problem"><div class="qid">${i+1}</div><div><div class="qtext">${esc(x.q)}</div><div class="meta">${esc(x.year)}｜${esc(x.exam)}｜${esc(x.qnum)}｜${status}</div><div class="hist"><span class="h">${esc(rating(x.id)||'未評価')}</span>${hhtml(x.id)}</div></div><div class="pick"><input data-id="${esc(x.id)}" type="checkbox" ${state.selected.includes(x.id)?'checked':''}></div></div>`});s+=`</div><div class="sticky"><button id="start" class="primary">演習開始（${state.selected.length}問）</button></div>`;V.innerHTML=s;V.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{const v=b.dataset.f;state.filters=state.filters.includes(v)?state.filters.filter(x=>x!==v):[...state.filters,v];state.selected=[];problems()});document.getElementById('all').onclick=()=>{state.selected=state.selected.length===q.length?[]:q.map(x=>x.id);problems()};V.querySelectorAll('[data-st]').forEach(e=>e.onchange=()=>{const ids=q.filter(x=>x.subtopic===e.dataset.st).map(x=>x.id);state.selected=e.checked?[...new Set([...state.selected,...ids])]:state.selected.filter(x=>!ids.includes(x));problems()});V.querySelectorAll('[data-id]').forEach(e=>e.onchange=()=>{state.selected=e.checked?[...new Set([...state.selected,e.dataset.id])]:state.selected.filter(x=>x!==e.dataset.id);saveLocal()});document.getElementById('start').onclick=()=>{if(!state.selected.length)return alert('1問以上選択してください。');M.classList.remove('hidden')}}
function shuffleBlocks(ids){const sm=window.QB_SERIES_MAP||{},selected=new Set(ids),blocks=[],seen=new Set();ids.forEach(id=>{if(seen.has(id))return;const full=sm[id];if(full){const block=full.filter(x=>selected.has(x));block.forEach(x=>seen.add(x));if(block.length)blocks.push(block)}else{seen.add(id);blocks.push([id])}});for(let i=blocks.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[blocks[i],blocks[j]]=[blocks[j],blocks[i]]}return blocks.flat()}
function pq(){return questions.find(x=>x.id===state.practice[state.pi])}window.pq=pq;
function rateBtns(q){return ['◎','○','△','×','-'].map(v=>`<button class="rate ${rating(q.id)===v?'on':''}" data-v="${v}">${v}</button>`).join('')}
function choiceExplanation(q,i){const c=q.choiceDetails[i]||{},parts=[];if(c.explanation)parts.push(c.explanation);if(c.correction_text)parts.push('修正：'+c.correction_text);if(c.correct_for_other_context)parts.push('別文脈：'+c.correct_for_other_context);if(c.examiner_distinction)parts.push('区別：'+c.examiner_distinction);return parts.join('<br>')|| (q.ans.includes(i)?'この問題では正しい選択肢。':'この問題では誤り。')}
function practice(){const q=pq();if(!q)return go('problems');const name=units.find(x=>x.slug===state.unitId)?.name||'';C.textContent=`和漢医学概論 ＞ ${name} ＞ 演習`;const modeLabel=q.answerMode==='single'?'1つ選択':'複数選択可';V.innerHTML=`<div class="row"><button id="back" class="btn">‹ 問題一覧</button><div style="text-align:right"><b>演習 ${state.pi+1}/${state.practice.length}問目</b><div class="meta">解答履歴 ${hist(q.id).length}/3件</div></div></div><div class="progress"><div style="width:${(state.pi+1)/state.practice.length*100}%"></div></div><div class="card" style="margin-top:12px"><div><span class="badge">${esc(q.year)}</span><span class="badge gray">${esc(q.exam)}</span><span class="badge gray">${esc(q.qnum)}</span><span class="badge gray">${modeLabel}</span></div><div class="title" style="margin-top:8px">${esc(q.q)}</div>${q.instruction?`<div class="sub">${esc(q.instruction)}</div>`:''}<div id="choices" class="choices"></div><div class="historybox"><b>直近3回の解答</b><div class="hist">${hhtml(q.id)}</div></div><div class="ratings"><span class="meta" style="align-self:center">自己評価：</span>${rateBtns(q)}</div><button id="submit" class="primary" style="margin-top:12px">${submitted?'もう一度解く':'解答する'}</button>${submitted?'':`<button id="reviewOnly" class="secondary" style="margin-top:8px">解答せずに解説を見る</button>`}</div><div id="ans" class="${submitted?'':'hidden'}"></div><div class="nav"><button id="prev" class="btn" ${state.pi===0?'disabled':''}>← 前の問題</button><button id="next" class="btn">${state.pi===state.practice.length-1?'演習終了':'次の問題 →'}</button></div>`;drawChoices();V.querySelectorAll('[data-v]').forEach(b=>b.onclick=async()=>{await setRating(q,b.dataset.v);practice()});document.getElementById('back').onclick=()=>{submitted=false;reviewOnly=false;sel=new Set();go('problems')};document.getElementById('submit').onclick=submitted?retry:submit;document.getElementById('reviewOnly')?.addEventListener('click',showExplanationOnly);document.getElementById('prev').onclick=()=>move(-1);document.getElementById('next').onclick=()=>state.pi===state.practice.length-1?finishSession():move(1);if(submitted)drawAnswer()}
function drawChoices(){const q=pq(),b=document.getElementById('choices');if(!q||!b)return;b.innerHTML='';q.choices.forEach((x,i)=>{const e=document.createElement('button');let cls='choice'+(sel.has(i)?' sel':'');if(submitted){if(q.ans.includes(i))cls+=' good';else if(sel.has(i))cls+=' bad'}e.className=cls;e.textContent=(submitted?(q.ans.includes(i)?'✓ ':sel.has(i)?'✕ ':''):'')+(q.choiceKeys[i]||String.fromCharCode(97+i))+'. '+x;e.disabled=submitted;e.onclick=()=>{if(q.answerMode==='single')sel=new Set([i]);else sel.has(i)?sel.delete(i):sel.add(i);drawChoices()};b.appendChild(e)})}
function same(a,b){return a.length===b.length&&[...a].sort((x,y)=>x-y).every((x,i)=>x===[...b].sort((x,y)=>x-y)[i])}
async function submit(){if(!sel.size)return alert('1つ以上選択してください。解答せず確認したい場合は「解答せずに解説を見る」を押してください。');const q=pq(),ok=same([...sel],q.ans);submitted=true;reviewOnly=false;try{await recordAnswer(q,ok);await setRating(q,ok?'○':'×');await saveSession(false)}catch(e){console.error(e);alert('学習履歴の保存に失敗しました。通信状況を確認してください。')}const d=document.createElement('div');d.className='fx '+(ok?'ok':'bad');d.textContent=ok?'✓ 正解！':'✕ 不正解';document.body.appendChild(d);setTimeout(()=>d.remove(),900);practice();requestAnimationFrame(()=>document.getElementById('ans')?.scrollIntoView({behavior:'smooth',block:'start'}))}
async function showExplanationOnly(){const q=pq();sel=new Set();reviewOnly=true;submitted=true;try{await recordReview(q);await setRating(q,'-');await saveSession(false)}catch(e){console.error(e);alert('閲覧状態の保存に失敗しました。通信状況を確認してください。')}practice();requestAnimationFrame(()=>document.getElementById('ans')?.scrollIntoView({behavior:'smooth',block:'start'}))}
function drawAnswer(){const q=pq(),ok=!reviewOnly&&same([...sel],q.ans),A=document.getElementById('ans');A.className='';A.innerHTML=`<div class="card resultcard ${reviewOnly?'review':ok?'ok':'bad'}"><div class="result ${reviewOnly?'':ok?'oktxt':'badtxt'}">${reviewOnly?'解説モード（未解答）':ok?'✓ 正解！':'✕ 不正解'}</div><b>正解：${q.ans.map(i=>esc(q.choiceKeys[i]||String.fromCharCode(97+i))).join('・')}　${q.ans.map(i=>esc(q.choices[i])).join('・')}</b>${reviewOnly?'<div class="meta" style="margin-top:6px">自己評価「-」。解答済み数には含みません。</div>':''}</div><div class="card"><b>■ 問題文のポイント</b><div class="line">${esc(q.note||'解説未登録')}</div></div><div class="card"><b>■ 各選択肢</b>${q.choices.map((c,i)=>`<div class="exp"><b>${esc(q.choiceKeys[i]||String.fromCharCode(97+i))}. ${q.ans.includes(i)?'○':'×'}　${esc(c)}</b><div class="line">${choiceExplanation(q,i)}</div></div>`).join('')}</div><div class="card"><b>■ 出題者の意図</b><div class="line">${esc(q.examinerIntent||'未登録')}</div></div><div class="card"><b>■ 試験用まとめ</b><div class="summary">${esc(q.examSummary||q.note||'未登録')}</div></div>${q.medicalVerificationNote?`<div class="card"><b>■ 医学的検証メモ</b><div class="line">${esc(q.medicalVerificationNote)}</div></div>`:''}`}
function retry(){sel=new Set();submitted=false;reviewOnly=false;practice();requestAnimationFrame(()=>scrollTo({top:0,behavior:'smooth'}))}
async function move(d){state.pi+=d;submitted=false;reviewOnly=false;sel=new Set();await saveSession(false);practice();scrollTo({top:0,behavior:'smooth'})}
async function finishSession(){await saveSession(true);state.practice=[];state.pi=0;state.sessionId=null;submitted=false;reviewOnly=false;sel=new Set();go('problems')}
M.querySelectorAll('[data-mode]').forEach(b=>b.onclick=async()=>{state.mode=b.dataset.mode;state.practice=state.mode==='shuffle'?shuffleBlocks(state.selected):[...state.selected];state.pi=0;state.sessionId=null;M.classList.add('hidden');submitted=false;reviewOnly=false;sel=new Set();await saveSession(false);go('practice')});document.getElementById('cancel').onclick=()=>M.classList.add('hidden');
H.onclick=()=>{if(state.screen==='units')return go('subjects');if(state.screen==='problems')return go('units');go('subjects')};
window.qbOpenSubjects=()=>go('subjects');
async function boot(){loadLocalState();V.innerHTML='<div class="card"><div class="title">読み込み中…</div><div class="sub">Supabaseから問題と学習履歴を取得しています。</div></div>';if(!(await waitForSupabase())){V.innerHTML='<div class="card"><div class="title">接続できませんでした</div><div class="sub">ログイン後に再読み込みしてください。</div></div>';return}try{await loadCatalog();await loadUserData();state.screen='subjects';render();saveLocal();findResume()}catch(e){console.error(e);V.innerHTML=`<div class="card"><div class="title">データ読み込みエラー</div><div class="sub">${esc(e.message||e)}</div></div>`}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
