(()=>{
'use strict';
const BUCKET='user-avatars';
let timer=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function css(){if(document.getElementById('rankingEntryCss'))return;const s=document.createElement('style');s.id='rankingEntryCss';s.textContent=`.header{flex-wrap:wrap}.qbAccountCluster{margin-left:auto;display:flex;align-items:center;gap:7px}.qbRankBtn{width:44px;height:44px;border:1px solid #dce3ec;background:#fff;border-radius:999px;display:grid;place-items:center;font-size:21px;text-decoration:none;color:#126fb3;font-weight:900}.acctBtn{margin-left:0!important}.acctAvatar.qbHasAvatar{background-size:cover;background-position:center;color:transparent}.qbAvatarBox{margin:8px 0 14px;padding:12px;border:1px solid #dce3ec;border-radius:13px;background:#f8fafc}.qbAvatarPreview{width:64px;height:64px;border-radius:50%;background:#126fb3;color:#fff;display:grid;place-items:center;font-weight:900;font-size:24px;background-size:cover;background-position:center}.qbAvatarTools{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:9px}.qbAvatarTools label,.qbAvatarRemove{border:1px solid #dce3ec;background:#fff;border-radius:10px;padding:8px 11px;color:#126fb3;font-weight:900;cursor:pointer}.qbAvatarTools input{display:none}@media(max-width:600px){.qbRankBtn{width:40px;height:40px}.qbAccountCluster{gap:5px}}`;document.head.appendChild(s)}
async function userAndProfile(){const sb=window.qbSupabase;if(!sb)return null;const {data:{user}}=await sb.auth.getUser();if(!user)return null;const r=await sb.from('profiles').select('id,display_name,avatar_path').eq('id',user.id).maybeSingle();return r.data?{user,profile:r.data}:null}
function publicUrl(path){if(!path||!window.qbSupabase)return '';return window.qbSupabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl||''}
function paintAvatar(path){const a=document.querySelector('#acctBtn .acctAvatar');if(!a)return;const u=publicUrl(path);a.classList.toggle('qbHasAvatar',!!u);a.style.backgroundImage=u?`url("${u}")`:''}
async function ensureHeader(){const h=document.querySelector('.header'),acct=document.getElementById('acctBtn');if(!h||!acct)return;let cluster=document.querySelector('.qbAccountCluster');if(!cluster){cluster=document.createElement('div');cluster.className='qbAccountCluster';const rank=document.createElement('a');rank.className='qbRankBtn';rank.href='./ranking.html';rank.setAttribute('aria-label','ランキング');rank.title='ランキング';rank.textContent='♛';h.insertBefore(cluster,acct);cluster.append(rank,acct)}else if(acct.parentElement!==cluster)cluster.appendChild(acct);const x=await userAndProfile();if(x)paintAvatar(x.profile.avatar_path)}
async function enhanceSheet(){const sheet=document.getElementById('acctSheet');if(!sheet||sheet.querySelector('.qbAvatarBox'))return;const panel=sheet.querySelector('.acctPanel');if(!panel)return;const x=await userAndProfile();if(!x)return;const {user,profile}=x,u=publicUrl(profile.avatar_path),initial=[...(profile.display_name||'U')][0]||'U';const box=document.createElement('div');box.className='qbAvatarBox';box.innerHTML=`<b>ユーザーアイコン</b><div class="qbAvatarPreview" style="${u?`background-image:url('${esc(u)}');color:transparent`:''}">${esc(initial)}</div><div class="qbAvatarTools"><label>画像を変更<input class="qbAvatarInput" type="file" accept="image/jpeg,image/png,image/webp"></label><button type="button" class="qbAvatarRemove">画像を削除</button><span class="muted qbAvatarMsg">JPEG / PNG / WebP・5MBまで</span></div>`;const sub=panel.querySelector('.authSub');sub?.insertAdjacentElement('afterend',box);const input=box.querySelector('.qbAvatarInput'),msg=box.querySelector('.qbAvatarMsg');input.onchange=async()=>{const f=input.files?.[0];if(!f)return;if(f.size>5*1024*1024){msg.textContent='5MB以下の画像を選んでください';return}msg.textContent='アップロード中…';const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=`${user.id}/avatar-${Date.now()}.${ext}`;const up=await window.qbSupabase.storage.from(BUCKET).upload(path,f,{upsert:false,contentType:f.type});if(up.error){msg.textContent='アップロード失敗: '+up.error.message;return}const old=profile.avatar_path;const r=await window.qbSupabase.from('profiles').update({avatar_path:path,updated_at:new Date().toISOString()}).eq('id',user.id);if(r.error){msg.textContent='保存失敗: '+r.error.message;return}profile.avatar_path=path;if(old)window.qbSupabase.storage.from(BUCKET).remove([old]).catch(()=>{});const url=publicUrl(path);box.querySelector('.qbAvatarPreview').style.backgroundImage=`url("${url}")`;box.querySelector('.qbAvatarPreview').style.color='transparent';paintAvatar(path);msg.textContent='変更しました'};box.querySelector('.qbAvatarRemove').onclick=async()=>{const old=profile.avatar_path;if(!old)return;msg.textContent='削除中…';const r=await window.qbSupabase.from('profiles').update({avatar_path:null,updated_at:new Date().toISOString()}).eq('id',user.id);if(r.error){msg.textContent='削除失敗: '+r.error.message;return}window.qbSupabase.storage.from(BUCKET).remove([old]).catch(()=>{});profile.avatar_path=null;const p=box.querySelector('.qbAvatarPreview');p.style.backgroundImage='';p.style.color='';paintAvatar(null);msg.textContent='削除しました'} }
function schedule(){clearTimeout(timer);timer=setTimeout(()=>{ensureHeader().catch(()=>{});enhanceSheet().catch(()=>{})},80)}
function boot(){css();schedule();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true});window.addEventListener('qb-app-ready',schedule);window.addEventListener('qb-screen-change',schedule)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();