'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium,webkit}=require('playwright'),root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://local').pathname;if(pathname==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head><meta charset="utf-8"><style>body{margin:0}*{box-sizing:border-box}</style></head><body><button id="origin">開く</button><div id="files"></div></body></html>');return}const file=path.resolve(root,'.'+decodeURIComponent(pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}try{res.setHeader('Content-Type',/\.m?js$/.test(file)?'application/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});
async function run(browser,label,url){
 const p=await browser.newPage({viewport:{width:1100,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(25000);await p.goto(url);
 for(const f of ['image-annotation-v1.css','file-media-v1.css'])await p.addStyleTag({url:url+f});
 for(const f of ['file-media-v1.js','image-annotation-model-v1.js','editable-media-v1.js','image-annotation-editor-v1.js','pdf-editor-v1.js','image-viewer.js'])await p.addScriptTag({url:url+f});
 // A previously saved crop with independent vector items and an immutable 4000px source.
 await p.evaluate(async()=>{
  const c=document.createElement('canvas');c.width=4000;c.height=2400;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.fillStyle='#ff0000';x.fillRect(400,400,800,400);for(let n=0;n<300;n++){x.fillStyle=n%2?'#000':'#fff';x.fillRect(1600+n,400,1,400)}window.raw=await new Promise(r=>c.toBlob(r,'image/png'));
  const base={assetId:'original',x:0,y:0,w:1000,h:600},reset={width:1000,height:600,base,items:[],counters:{number:1,letter:1}};
  const scene={...structuredClone(reset),width:800,height:500,base:{...base,x:-100,y:-50},cropOrigin:{width:1000,height:600,x:100,y:50},items:[{id:'ink',type:'pen',color:'#0000ff',width:5,points:[{x:200,y:100},{x:500,y:100}]},{id:'text',type:'text',x:200,y:180,w:200,h:42,fontSize:32,text:'編集できる',color:'#111111'}]};
  const record={scene,reset,assets:new Map([['original',raw]])},prepared=await QBEditableMedia.prepare(record);window.saved=await QBEditableMedia.write(await QBEditableMedia.preview(scene,prepared.assets),record);prepared.dispose();window.before=await saved.arrayBuffer();QBImageEditor.open(saved,{onSave:async b=>window.saved=b});
 });
 await p.locator('.qbDrawSave:enabled').waitFor();await p.getByRole('button',{name:'全体のトリミングを解除',exact:true}).click();await p.locator('.qbDrawSave').click();await p.locator('.qbDrawModal').waitFor({state:'detached'});
 let check=await p.evaluate(async()=>{const r=await QBEditableMedia.read(saved),raw2=r.assets.get(r.scene.base.assetId),im=await createImageBitmap(saved);return{width:r.scene.width,items:r.scene.items.map(i=>i.type),bytes:await raw2.text()===await raw.text(),preview:im.width,origin:!!r.scene.cropOrigin}});
 assert.equal(check.width,1000);assert.deepEqual(check.items,['pen','text']);assert.equal(check.bytes,true);assert.equal(check.origin,false);assert.ok(check.preview<=2400);
 // Reopen and remove just one stroke using the selection tool, then undo it.
 await p.evaluate(()=>{QBImageEditor.open(saved,{onSave:async b=>window.saved=b})});
 await p.locator('.qbDrawSave:enabled').waitFor();await p.getByRole('button',{name:'投げ縄',exact:true}).click();await p.getByRole('button',{name:'全体表示',exact:true}).click();let box=await p.locator('.qbDrawStage').boundingBox(),z=Math.min((box.width-32)/1000,(box.height-32)/600);await p.mouse.click(box.x+(box.width-1000*z)/2+450*z,box.y+(box.height-600*z)/2+150*z);await p.keyboard.press('Delete');await p.getByRole('button',{name:'↶ 元に戻す',exact:true}).click();await p.locator('.qbDrawSave').click();await p.locator('.qbDrawModal').waitFor({state:'detached'});
 assert.equal(await p.evaluate(async()=>(await QBEditableMedia.read(saved)).scene.items.length),2);
 // Clipboard copies preserve a cropped, editable document without unpacking its clip.
 await p.evaluate(async()=>{window.copySource=saved;const c=document.createElement('canvas');c.width=1000;c.height=600;c.getContext('2d').fillRect(0,0,1000,600);const raw=await new Promise(r=>c.toBlob(r));QBImageEditor.open(raw,{onSave:async b=>window.parentSaved=b})});await p.locator('.qbDrawSave:enabled').waitFor();
 await p.locator('.qbDrawCanvas').evaluate(n=>{const d=new DataTransfer();d.items.add(new File([copySource],'copy.png',{type:'image/png'}));n.dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}))});await p.locator('.qbDrawEditSelected:visible').waitFor();
 await p.locator('.qbDrawEditSelected').click();await p.getByRole('dialog',{name:'選択画像を編集',exact:true}).waitFor();await p.locator('.qbDrawModal:not([hidden]) .qbDrawSave:enabled').waitFor();p.once('dialog',d=>d.accept());await p.locator('.qbDrawModal:not([hidden]) .qbDrawReset').click();await p.locator('.qbDrawModal:not([hidden]) .qbDrawSave').click();await p.getByRole('dialog',{name:'選択画像を編集',exact:true}).waitFor({state:'detached'});await p.locator('.qbDrawSave').click();await p.locator('.qbDrawModal').waitFor({state:'detached'});
 check=await p.evaluate(async()=>{const a=await QBEditableMedia.read(parentSaved),nested=await QBEditableMedia.read(a.assets.get(a.scene.items[0].assetId)),original=await QBEditableMedia.read(copySource);return{count:a.scene.items.length,nested:nested.scene.items.length,original:original.scene.items.length}});assert.deepEqual(check,{count:1,nested:0,original:2});
 // Zoom renders original sources instead of enlarging the small PNG preview.
 await p.evaluate(()=>{const img=document.createElement('img');img.className='qbMediaImg';img.src=URL.createObjectURL(saved);img.qbEditMedia=async()=>{await QBImageEditor.open(saved,{onSave:async b=>{window.saved=b;img.src=URL.createObjectURL(b)}})};document.getElementById('files').append(img)});await p.locator('.qbMediaImg').click();await p.locator('.qbEditableZoom').waitFor();await p.getByRole('button',{name:'拡大',exact:true}).click();assert.ok(await p.locator('.qbEditableZoom').evaluate(c=>c.width>500));await p.getByRole('button',{name:'画像編集',exact:true}).click();await p.locator('.qbDrawSave:enabled').waitFor();await p.locator('.qbDrawSave').click();await p.locator('.qbDrawModal').waitFor({state:'detached'});await p.locator('.qbEditableZoom').waitFor();await p.locator('.qbImageLightboxClose').click();
 // Native PDF export retains image dimensions; actual rendered colors catch y flips.
 check=await p.evaluate(async()=>{const record=await QBEditableMedia.read(saved),out=await QBEditableMedia.exportPDF(record),task=await QBFiles.documentTask(out),doc=await task.promise,page=await doc.getPage(1),vp=page.getViewport({scale:1}),c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;await page.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;const x=c.getContext('2d'),pixels=[[150,150],[350,150],[450,150],[250,250]].map(([a,b])=>[...x.getImageData(a,b,1,1).data]);const ops=await page.getOperatorList(),engine=await import('/vendor/pdfjs/pdf.mjs');let dims=[];for(let i=0;i<ops.fnArray.length;i++)if(ops.fnArray[i]===engine.OPS.paintImageXObject)dims.push(ops.argsArray[i].slice(1));await task.destroy();return{pixels,dims}});assert.deepEqual(check.pixels[0],[255,0,0,255]);assert.deepEqual(check.pixels[1],[0,0,255,255]);assert.deepEqual(check.pixels[2],[0,0,255,255]);assert.ok(check.dims.some(([w,h])=>w===4000&&h===2400));
 // Create a charcoal multipage PDF, save it, reopen it and add another blank page.
 await p.evaluate(()=>{window.blank=null;QBPDFEditor.create({onSave:async b=>window.blank=b})});await p.getByRole('button',{name:'横',exact:true}).click();await p.getByLabel('背景色',{exact:true}).selectOption('charcoal');
 const formColors=await p.locator('.qbPdfCreate .qbPdfStage').evaluate(n=>({background:getComputedStyle(n).backgroundColor,color:getComputedStyle(n).color}));assert.deepEqual(formColors,{background:'rgb(255, 255, 255)',color:'rgb(23, 32, 51)'});await p.setViewportSize({width:390,height:844});assert.ok(await p.locator('.qbPdfCreate').evaluate(n=>n.getBoundingClientRect().right<=innerWidth));await p.screenshot({path:'test-results/ui/pdf-create-settings-'+label+'.png'});
 await p.getByRole('button',{name:'作成して編集',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 1ページ');await p.getByRole('button',{name:'白紙ページを追加',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent.startsWith('2 / 2'));await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});
 check=await p.evaluate(async()=>{const t=await QBFiles.documentTask(blank),d=await t.promise,page=await d.getPage(1),v=page.getViewport({scale:.1}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await page.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const rgba=[...c.getContext('2d').getImageData(5,5,1,1).data],n=d.numPages;await t.destroy();return{n,rgba,width:v.width,height:v.height}});assert.ok(check.width>check.height);assert.equal(check.n,2);assert.ok(check.rgba[0]>=35&&check.rgba[0]<=45);assert.equal(check.rgba[0],check.rgba[1]);
 await p.evaluate(()=>{QBPDFEditor.open(blank,{onSave:async b=>window.blank=b})});await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 2ページ');await p.getByRole('button',{name:'白紙ページを追加',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent.startsWith('3 / 3'));await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});
 await p.evaluate(()=>{QBPDFEditor.create({onSave:async b=>window.blank=b})});await p.getByRole('button',{name:'作成して編集',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 1ページ');await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});assert.ok(await p.evaluate(async()=>{const t=await QBFiles.documentTask(blank),d=await t.promise,v=(await d.getPage(1)).getViewport({scale:1});await t.destroy();return v.width<v.height}));
 assert.deepEqual(errors,[]);await p.close();console.log(label+' PASS original-byte preservation, save/reopen/uncrop, editable independent copies, high-resolution zoom and edit return, native PDF images and vector paths, charcoal multipage creation');
}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));try{for(const [label,type] of [['Chromium',chromium],['WebKit',webkit]]){const b=await type.launch();try{await run(b,label,`http://127.0.0.1:${server.address().port}/`)}finally{await b.close()}}}finally{server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
