'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium,webkit}=require('playwright'),root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://local').pathname;if(pathname==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head><meta charset="utf-8"><style>body{margin:0}*{box-sizing:border-box}</style></head><body><button id="origin">開く</button><div id="files"></div></body></html>');return}const file=path.resolve(root,'.'+decodeURIComponent(pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}try{res.setHeader('Content-Type',/\.m?js$/.test(file)?'application/javascript':file.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});
async function run(browser,label,url){
 const p=await browser.newPage({viewport:{width:1100,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(25000);await p.goto(url);
 for(const f of ['image-annotation-v1.css','file-media-v1.css'])await p.addStyleTag({url:url+f});
 for(const f of ['file-media-v1.js','image-annotation-model-v1.js','editable-media-v1.js','image-annotation-editor-v1.js','pdf-editor-v1.js','image-viewer.js','image-editor-source-picker-v1.js'])await p.addScriptTag({url:url+f});
 // A library picker opened from PDF creation/editing must sit above the PDF modal.
 await p.evaluate(()=>{window.QBImageLibraryStore={authorize:async()=>{},search:async()=>[],catalog:async()=>[],signedURL:async()=>''};window.qbSupabase={};window.layeredCreate=QBPDFEditor.create();window.layeredPick=QBImageEditorSources.pickLibrary({sb:qbSupabase,title:'重なり順確認',noun:'ファイル'})});await p.locator('.qbeSourceModal').waitFor();assert.ok(await p.evaluate(()=>Number(getComputedStyle(document.querySelector('.qbeSourceModal')).zIndex)>Number(getComputedStyle(document.querySelector('.qbPdfModal')).zIndex)));await p.locator('.qbeCancel').click();await p.getByRole('button',{name:'キャンセル',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});
 // A previously saved crop with independent vector items and an immutable 4000px source.
 await p.evaluate(async()=>{
  const c=document.createElement('canvas');c.width=4000;c.height=2400;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.fillStyle='#ff0000';x.fillRect(400,400,800,400);for(let n=0;n<300;n++){x.fillStyle=n%2?'#000':'#fff';x.fillRect(1600+n,400,1,400)}window.raw=await new Promise(r=>c.toBlob(r,'image/png'));
  const base={assetId:'original',x:0,y:0,w:1000,h:600},reset={width:1000,height:600,base,items:[],counters:{number:1,letter:1}};
  const scene={...structuredClone(reset),width:800,height:500,base:{...base,x:-100,y:-50},cropOrigin:{width:1000,height:600,x:100,y:50},items:[{id:'ink',type:'pen',color:'#0000ff',width:5,points:[{x:200,y:100},{x:500,y:100}]},{id:'text',type:'text',x:200,y:180,w:200,h:42,fontSize:32,text:'編集できる',color:'#111111'}]};
  const record={scene,reset,assets:new Map([['original',raw]])},prepared=await QBEditableMedia.prepare(record);window.saved=await QBEditableMedia.write(await QBEditableMedia.preview(scene,prepared.assets),record);prepared.dispose();window.before=await saved.arrayBuffer();QBImageEditor.open(saved,{onSave:async b=>window.saved=b});
 });
 await p.locator('.qbDrawSave:enabled').waitFor();await p.getByRole('button',{name:'全体のトリミングを解除',exact:true}).click();await p.locator('.qbDrawSave').click();await p.locator('.qbDrawModal').waitFor({state:'detached'});
 let check=await p.evaluate(async()=>{const r=await QBEditableMedia.read(saved),raw2=r.assets.get(r.scene.base.assetId),im=await createImageBitmap(saved);return{width:r.scene.width,items:r.scene.items.map(i=>i.type),bytes:await raw2.text()===await raw.text(),preview:im.width,origin:!!r.scene.cropOrigin}});
 assert.equal(check.width,1000);assert.deepEqual(check.items,['pen','text']);assert.equal(check.bytes,true);assert.equal(check.origin,false);assert.ok(check.preview<=2400);
 // Reopen and remove just one stroke using the selection tool, then undo it.
 await p.evaluate(()=>{QBImageEditor.open(saved,{onSave:async b=>window.saved=b})});
 await p.locator('.qbDrawSave:enabled').waitFor();await p.getByRole('button',{name:'投げ縄',exact:true}).click();await p.getByRole('button',{name:'全体表示',exact:true}).click();let box=await p.locator('.qbDrawStage').boundingBox(),z=Math.min((box.width-32)/1000,(box.height-32)/600);await p.mouse.click(box.x+(box.width-1000*z)/2+450*z,box.y+(box.height-600*z)/2+150*z);await p.keyboard.press('Delete');await p.getByRole('button',{name:'↶ 元に戻す',exact:true}).click();await p.locator('.qbDrawSave').click();await p.locator('.qbDrawModal').waitFor({state:'detached'});
 assert.equal(await p.evaluate(async()=>(await QBEditableMedia.read(saved)).scene.items.length),2);
 // Clipboard copies preserve a cropped, editable document without unpacking its clip.
 await p.evaluate(async()=>{window.copySource=saved;const c=document.createElement('canvas');c.width=1000;c.height=600;c.getContext('2d').fillRect(0,0,1000,600);const raw=await new Promise(r=>c.toBlob(r));QBImageEditor.open(raw,{onSave:async b=>window.parentSaved=b})});await p.locator('.qbDrawSave:enabled').waitFor();
 await p.locator('.qbDrawCanvas').evaluate(n=>{const d=new DataTransfer();d.items.add(new File([copySource],'copy.png',{type:'image/png'}));n.dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}))});await p.locator('.qbDrawEditSelected:visible').waitFor();
 await p.locator('.qbDrawEditSelected').click();await p.getByRole('dialog',{name:'選択画像を編集',exact:true}).waitFor();await p.locator('.qbDrawModal:not([hidden]) .qbDrawSave:enabled').waitFor();p.once('dialog',d=>d.accept());await p.locator('.qbDrawModal:not([hidden]) .qbDrawReset').click();await p.locator('.qbDrawModal:not([hidden]) .qbDrawSave').click();await p.getByRole('dialog',{name:'選択画像を編集',exact:true}).waitFor({state:'detached'});await p.locator('.qbDrawSave').click();await p.locator('.qbDrawModal').waitFor({state:'detached'});
 check=await p.evaluate(async()=>{const a=await QBEditableMedia.read(parentSaved),nested=await QBEditableMedia.read(a.assets.get(a.scene.items[0].assetId)),original=await QBEditableMedia.read(copySource);return{count:a.scene.items.length,nested:nested.scene.items.length,original:original.scene.items.length}});assert.deepEqual(check,{count:1,nested:0,original:2});
 // Zoom renders original sources instead of enlarging the small PNG preview.
 await p.evaluate(()=>{const img=document.createElement('img');img.className='qbMediaImg';img.src=URL.createObjectURL(saved);img.qbEditMedia=async()=>{await QBImageEditor.open(saved,{onSave:async b=>{window.saved=b;img.src=URL.createObjectURL(b)}})};document.getElementById('files').append(img)});await p.locator('.qbMediaImg').click();await p.locator('.qbEditableZoom').waitFor();await p.getByRole('button',{name:'拡大',exact:true}).click();assert.ok(await p.locator('.qbEditableZoom').evaluate(c=>c.width>500));await p.getByRole('button',{name:'画像編集',exact:true}).click();await p.locator('.qbDrawSave:enabled').waitFor();await p.locator('.qbDrawSave').click();await p.locator('.qbDrawModal').waitFor({state:'detached'});await p.locator('.qbEditableZoom').waitFor();await p.locator('.qbImageLightboxClose').click();
 // Native PDF export retains image dimensions; actual rendered colors catch y flips.
 check=await p.evaluate(async()=>{const record=await QBEditableMedia.read(saved),out=await QBEditableMedia.exportPDF(record),task=await QBFiles.documentTask(out),doc=await task.promise,page=await doc.getPage(1),vp=page.getViewport({scale:1}),c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;await page.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;const x=c.getContext('2d'),pixels=[[150,150],[350,150],[450,150],[250,250]].map(([a,b])=>[...x.getImageData(a,b,1,1).data]);const ops=await page.getOperatorList(),engine=await import('/vendor/pdfjs/pdf.mjs');let dims=[];for(let i=0;i<ops.fnArray.length;i++)if(ops.fnArray[i]===engine.OPS.paintImageXObject)dims.push(ops.argsArray[i].slice(1));await task.destroy();return{pixels,dims}});assert.deepEqual(check.pixels[0],[255,0,0,255]);assert.deepEqual(check.pixels[1],[0,0,255,255]);assert.deepEqual(check.pixels[2],[0,0,255,255]);assert.ok(check.dims.some(([w,h])=>w===4000&&h===2400));
 // New PDFs can start directly from selected or pasted images, one page per image.
 const createPNG=Buffer.from(await p.evaluate(async()=>[...new Uint8Array(await raw.arrayBuffer())]));
 await p.evaluate(()=>{window.fromImages=null;QBPDFEditor.create({onSave:async b=>window.fromImages=b})});await p.locator('[data-create-files]').setInputFiles([{name:'one.png',mimeType:'image/png',buffer:createPNG},{name:'two.png',mimeType:'image/png',buffer:createPNG}]);await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 2ページ');await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});assert.equal(await p.evaluate(async()=>{const t=await QBFiles.documentTask(fromImages),d=await t.promise,n=d.numPages;await t.destroy();return n}),2);
 await p.evaluate(()=>{window.fromPaste=null;QBPDFEditor.create({onSave:async b=>window.fromPaste=b})});await p.getByRole('button',{name:'ペーストから作成',exact:true}).click();await p.evaluate(()=>{const d=new DataTransfer();d.items.add(new File([raw],'paste.png',{type:'image/png'}));document.querySelector('.qbPdfModal').dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}))});await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 1ページ');await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});assert.equal(await p.evaluate(async()=>{const t=await QBFiles.documentTask(fromPaste),d=await t.promise,n=d.numPages;await t.destroy();return n}),1);
 await p.evaluate(()=>{window.fromPdfPaste=null;QBPDFEditor.create({onSave:async b=>window.fromPdfPaste=b})});await p.getByRole('button',{name:'ペーストから作成',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfCreate [role=status]')?.textContent.includes('貼り付け待機中'));await p.evaluate(()=>{const d=new DataTransfer();d.items.add(new File([fromImages],'copied.pdf',{type:'application/pdf'}));document.querySelector('.qbPdfModal').dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}))});await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 2ページ');await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});assert.equal(await p.evaluate(async()=>{const t=await QBFiles.documentTask(fromPdfPaste),d=await t.promise,n=d.numPages;await t.destroy();return n}),2);
 // Margins enlarge only the current page and keep its original PDF content at native quality.
 await p.evaluate(()=>{window.withMargins=null;QBPDFEditor.open(fromImages,{initialPage:2,onSave:async b=>window.withMargins=b})});await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='2 / 2ページ');await p.getByRole('button',{name:'余白を追加',exact:true}).click();await p.getByLabel('上',{exact:true}).fill('10');await p.getByLabel('右',{exact:true}).fill('5');await p.getByLabel('下',{exact:true}).fill('7');await p.getByLabel('左',{exact:true}).fill('3');await p.getByRole('button',{name:'余白を追加する',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent.startsWith('2 / 2ページ'));await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});
 check=await p.evaluate(async()=>{const before=await QBFiles.documentTask(fromImages),after=await QBFiles.documentTask(withMargins),a=await before.promise,b=await after.promise,v1=(await a.getPage(1)).getViewport({scale:1}),v2=(await a.getPage(2)).getViewport({scale:1}),m1=(await b.getPage(1)).getViewport({scale:1}),m2=(await b.getPage(2)).getViewport({scale:1});await before.destroy();await after.destroy();return{same:[m1.width-v1.width,m1.height-v1.height],added:[m2.width-v2.width,m2.height-v2.height]}});assert.ok(Math.abs(check.same[0])<.01&&Math.abs(check.same[1])<.01);assert.ok(Math.abs(check.added[0]-8*72/25.4)<.1&&Math.abs(check.added[1]-17*72/25.4)<.1);
 // PDF creation can also pull current copies from recent files and the image library.
 await p.evaluate(()=>{
  window.fromRecent=null;
  window.qbRecentImagePicker={pick:async options=>{window.recentCreateOptions=options;return[{id:'recent-image',image_path:'recent/image.png'},{id:'recent-pdf',image_path:'recent/document.pdf'}]}};
  window.qbSupabase={
   from:()=>({select(){return this},eq(key,id){this.path=id==='recent-pdf'?'recent/document.pdf':'recent/image.png';return this},async maybeSingle(){return{data:{image_path:this.path},error:null}}}),
   storage:{from:()=>({download:async path=>({data:path.endsWith('.pdf')?fromImages:raw,error:null})})}
  };
  QBPDFEditor.create({onSave:async b=>window.fromRecent=b});
 });
 await p.getByRole('button',{name:'最近の画像・PDFから作成',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');assert.equal(await p.evaluate(()=>recentCreateOptions.noun),'ファイル');await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});
 await p.evaluate(()=>{window.fromLibrary=null;window.QBImageEditorSources={pickLibrary:async options=>{window.libraryCreateOptions=options;return[{id:'library-pdf',revision:4,object_path:'library/document.pdf'}]}};window.QBImageLibraryStore={get:async()=>({id:'library-pdf',revision:4,object_path:'library/document.pdf',archived:false}),download:async()=>fromImages};QBPDFEditor.create({onSave:async b=>window.fromLibrary=b})});
 await p.getByRole('button',{name:'ライブラリから作成',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 2ページ');assert.deepEqual(await p.evaluate(()=>({title:libraryCreateOptions.title,noun:libraryCreateOptions.noun})),{title:'ライブラリからPDFを作成',noun:'ファイル'});await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});
 // Existing PDFs expose the same paste, device, recent and library sources at the requested edit-screen button.
 await p.evaluate(()=>{window.editImported=null;QBPDFEditor.open(fromImages,{initialPage:2,onSave:async b=>window.editImported=b})});await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='2 / 2ページ');
 const openImport=async()=>{await p.getByRole('button',{name:'画像・PDFからページを追加',exact:true}).click();await p.locator('.qbPdfImportChoices:not([hidden])').waitFor()};
 await openImport();assert.deepEqual(await p.locator('.qbPdfImportChoicesPanel button').allTextContents(),['コピーした画像・PDFをペースト','端末の画像・PDFを選択','最近の画像・PDFから選択','ライブラリから選択','閉じる']);
 await p.getByRole('button',{name:'コピーした画像・PDFをペースト',exact:true}).click();await p.evaluate(()=>{const d=new DataTransfer();d.items.add(new File([raw],'added-from-paste.png',{type:'image/png'}));document.querySelector('.qbPdfModal').dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}))});await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent.startsWith('3 / 3ページ'));
 await openImport();await p.getByRole('button',{name:'最近の画像・PDFから選択',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent.startsWith('4 / 6ページ'));assert.equal(await p.evaluate(()=>recentCreateOptions.title),'追加する画像・PDFを選択');
 await openImport();await p.getByRole('button',{name:'ライブラリから選択',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent.startsWith('5 / 8ページ'));assert.equal(await p.evaluate(()=>libraryCreateOptions.title),'追加する画像・PDFを選択');
 await openImport();await p.locator('[data-import]').setInputFiles([{name:'device-image.png',mimeType:'image/png',buffer:createPNG},{name:'device-pages.pdf',mimeType:'application/pdf',buffer:Buffer.from(await p.evaluate(async()=>[...new Uint8Array(await fromImages.arrayBuffer())]))}]);await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent.startsWith('6 / 11ページ'));await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});assert.equal(await p.evaluate(async()=>{const t=await QBFiles.documentTask(editImported),d=await t.promise,n=d.numPages;await t.destroy();return n}),11);
 // Create a charcoal multipage PDF, save it, reopen it and add another blank page.
 await p.evaluate(()=>{window.blank=null;QBPDFEditor.create({onSave:async b=>window.blank=b})});await p.getByRole('button',{name:'横',exact:true}).click();await p.getByLabel('背景色',{exact:true}).selectOption('charcoal');
 const formColors=await p.locator('.qbPdfCreate .qbPdfStage').evaluate(n=>({background:getComputedStyle(n).backgroundColor,color:getComputedStyle(n).color}));assert.deepEqual(formColors,{background:'rgb(255, 255, 255)',color:'rgb(23, 32, 51)'});await p.setViewportSize({width:390,height:844});assert.ok(await p.locator('.qbPdfCreate').evaluate(n=>n.getBoundingClientRect().right<=innerWidth));await p.screenshot({path:'test-results/ui/pdf-create-settings-'+label+'.png'});
 await p.getByRole('button',{name:'白紙を作成して編集',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 1ページ');await p.waitForFunction(()=>{const c=document.querySelector('.qbPdfViewingStage canvas')?.getBoundingClientRect(),s=document.querySelector('.qbPdfViewingStage')?.getBoundingClientRect();return c&&s&&c.left>=s.left+23&&c.right<=s.right-23&&c.top>=s.top+23&&c.bottom<=s.bottom-23});await p.getByRole('button',{name:'白紙ページを追加',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent.startsWith('2 / 2'));await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});
 check=await p.evaluate(async()=>{const t=await QBFiles.documentTask(blank),d=await t.promise,page=await d.getPage(1),v=page.getViewport({scale:.1}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await page.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const rgba=[...c.getContext('2d').getImageData(5,5,1,1).data],n=d.numPages;await t.destroy();return{n,rgba,width:v.width,height:v.height}});assert.ok(check.width>check.height);assert.equal(check.n,2);assert.ok(check.rgba[0]>=35&&check.rgba[0]<=45);assert.equal(check.rgba[0],check.rgba[1]);
 await p.evaluate(()=>{QBPDFEditor.open(blank,{onSave:async b=>window.blank=b})});await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 2ページ');await p.getByRole('button',{name:'白紙ページを追加',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent.startsWith('2 / 3'));await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});
 await p.evaluate(()=>{QBPDFEditor.create({onSave:async b=>window.blank=b})});await p.getByRole('button',{name:'白紙を作成して編集',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 1ページ');await p.waitForFunction(()=>{const c=document.querySelector('.qbPdfViewingStage canvas')?.getBoundingClientRect(),s=document.querySelector('.qbPdfViewingStage')?.getBoundingClientRect();return c&&s&&c.left>=s.left+23&&c.right<=s.right-23&&c.top>=s.top+23&&c.bottom<=s.bottom-23});await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});assert.ok(await p.evaluate(async()=>{const t=await QBFiles.documentTask(blank),d=await t.promise,v=(await d.getPage(1)).getViewport({scale:1});await t.destroy();return v.width<v.height}));
 assert.deepEqual(errors,[]);await p.close();console.log(label+' PASS original-byte preservation, save/reopen/uncrop, editable independent copies, high-resolution zoom and edit return, native PDF images and vector paths, charcoal multipage creation');
}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));try{for(const [label,type] of [['Chromium',chromium],['WebKit',webkit]]){const b=await type.launch();try{await run(b,label,`http://127.0.0.1:${server.address().port}/`)}finally{await b.close()}}}finally{server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
