'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium,webkit}=require('playwright');
const root=path.resolve(__dirname,'..');
const pdfFixture=require('./pdf-fixture.cjs');
const fixture=pdfFixture();
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://local').pathname;res.setHeader('Access-Control-Allow-Origin','*');if(pathname==='/fixture.pdf'){res.setHeader('Content-Type','application/pdf');res.end(fixture);return}const file=path.resolve(root,'.'+decodeURIComponent(pathname));if(pathname!=='/'&&!file.startsWith(root+path.sep)){res.writeHead(403).end();return}if(pathname==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head><meta charset="utf-8"></head><body><button id="origin">開く</button><div id="files"></div></body></html>');return}try{res.setHeader('Content-Type',file.endsWith('.mjs')||file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});
async function run(browser,label,url){
 const p=await browser.newPage({viewport:{width:1024,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'||m.type()==='warning')console.log(label+' PDF console: '+m.text())});p.setDefaultTimeout(20000);await p.goto(url);await p.addStyleTag({url:url+'file-media-v1.css'});await p.addScriptTag({url:url+'file-media-v1.js'});
 await p.evaluate(()=>document.querySelector('#files').innerHTML=QBFiles.markup('/fixture.pdf'));
 await p.waitForFunction(()=>document.querySelector('[data-pdf-pages="3"]'));
 assert.equal(await p.locator('#files img').count(),0);await p.locator('.qbPdfCard').click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');
 assert.equal(await p.locator('#origin').evaluate(n=>n.inert),true);
 const color=()=>p.locator('.qbPdfPage').evaluate(c=>Array.from(c.getContext('2d').getImageData(10,10,1,1).data));
 assert.deepEqual(await color(),[255,0,0,255]);await p.getByRole('button',{name:'2ページを表示',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='2 / 3ページ');assert.deepEqual(await color(),[0,255,0,255]);
 await p.getByRole('button',{name:'＋',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='2 / 3ページ');assert.deepEqual(await color(),[0,255,0,255]);await p.waitForFunction(()=>document.querySelectorAll('.qbPdfPageStrip canvas').length===3);
 await p.getByRole('button',{name:'閉じる',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});assert.equal(await p.locator('#origin').evaluate(n=>n.inert),false);
 await p.evaluate(async()=>{const blob=await (await fetch('/fixture.pdf')).blob();window.sourcePDF=blob;window.pageImage=undefined;QBFiles.open(blob,{pickPage:true}).then(b=>window.pageImage=b)});await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');await p.getByRole('button',{name:'3ページを表示',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='3 / 3ページ');await p.getByRole('button',{name:'このページを画像として追加',exact:true}).click();await p.waitForFunction(()=>window.pageImage instanceof Blob);
 const exported=await p.evaluate(async()=>{const b=await createImageBitmap(pageImage),c=document.createElement('canvas');c.width=b.width;c.height=b.height;const x=c.getContext('2d');x.drawImage(b,0,0);return{type:pageImage.type,w:b.width,h:b.height,pixel:[...x.getImageData(10,10,1,1).data],source:await sourcePDF.text()}});assert.equal(exported.type,'image/png');assert.deepEqual(exported.pixel,[0,0,255,255]);assert.equal(exported.source,fixture.toString());
 const paste=await p.evaluate(async()=>{const d=new DataTransfer();d.items.add(new File([sourcePDF],'test.pdf',{type:'application/pdf'}));d.items.add(new File(['image'],'x.png',{type:'image/png'}));d.setData('text/plain','keep text');const e=new ClipboardEvent('paste',{clipboardData:d});const files=QBFiles.filesFromPaste(e);let rejected=false;try{await QBFiles.validate(new File(['not PDF'],'fake.pdf',{type:'application/pdf'}))}catch{rejected=true}return {types:files.map(f=>f.type),prevented:e.defaultPrevented,rejected}});assert.deepEqual(paste,{types:['application/pdf','image/png'],prevented:false,rejected:true});
 fs.mkdirSync(path.join(root,'test-results/ui'),{recursive:true});await p.screenshot({path:path.join(root,`test-results/ui/${label}-file-card.png`)});
 assert.deepEqual(errors,[]);await p.close();console.log(label+' PASS real PDF thumbnail, page navigation, bounded thumbnails, zoom, explicit PNG extraction, paste types and source preservation');
}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));try{for(const [label,type] of [['Chromium',chromium],['WebKit',webkit]]){const b=await type.launch();try{await run(b,label,`http://127.0.0.1:${server.address().port}/`)}finally{await b.close()}}}finally{server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
