'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium,webkit}=require('playwright');
const root=path.resolve(__dirname,'..');
const pdfFixture=require('./pdf-fixture.cjs');
const fixture=pdfFixture();
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://local').pathname;res.setHeader('Access-Control-Allow-Origin','*');if(pathname==='/fixture.pdf'){res.setHeader('Content-Type','application/pdf');res.end(fixture);return}const file=path.resolve(root,'.'+decodeURIComponent(pathname));if(pathname!=='/'&&!file.startsWith(root+path.sep)){res.writeHead(403).end();return}if(pathname==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head><meta charset="utf-8"></head><body><button id="origin">開く</button><div id="files"></div></body></html>');return}try{res.setHeader('Content-Type',file.endsWith('.mjs')||file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});
async function run(browser,label,url){
 const p=await browser.newPage({viewport:{width:1024,height:800},deviceScaleFactor:2}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error'||m.type()==='warning')console.log(label+' PDF console: '+m.text())});p.setDefaultTimeout(20000);await p.goto(url);await p.addStyleTag({url:url+'file-media-v1.css'});await p.addScriptTag({url:url+'file-media-v1.js'});await p.addScriptTag({url:url+'media-share-v1.js'});
 await p.evaluate(()=>document.querySelector('#files').innerHTML=QBFiles.markup('/fixture.pdf'));
 await p.waitForFunction(()=>document.querySelector('[data-inline-page="1"] canvas'));
 for(const page of ['2','3','1']){await p.locator(`[data-inline-page="${page}"]`).scrollIntoViewIfNeeded();await p.waitForFunction(page=>document.querySelector(`[data-inline-page="${page}"] canvas`),page)}
 const stableInline=await p.evaluate(()=>({canvases:document.querySelectorAll('[data-inline-page] canvas').length,loads:performance.getEntriesByType('resource').filter(entry=>new URL(entry.name).pathname==='/fixture.pdf').length}));
 assert.deepEqual(stableInline,{canvases:3,loads:1});
 let flakyLoads=0;await p.route('**/flaky-inline.pdf',route=>{flakyLoads++;return flakyLoads===1?route.fulfill({status:503,body:'temporary unavailable'}):route.fulfill({contentType:'application/pdf',body:fixture})});
 await p.evaluate(()=>{const host=document.createElement('div');host.id='flakyInline';host.innerHTML=QBFiles.markup('/flaky-inline.pdf');document.body.append(host)});
 await p.waitForFunction(()=>document.querySelector('#flakyInline [data-inline-page="1"] canvas'));
 assert.equal(flakyLoads,2);assert.doesNotMatch(await p.locator('#flakyInline .qbPdfCaption').textContent(),/読み込み待ち|再読み込み中/);
 await p.locator('#flakyInline').evaluate(n=>n.remove());
 await p.waitForFunction(()=>document.querySelectorAll('.qbPdfCard>.qbMediaShareButton').length===1);assert.equal(await p.locator('.qbPdfInlinePage>.qbMediaShareButton').count(),0);
 await p.locator('.qbPdfCard>.qbMediaShareButton').click();await p.locator('.qbMediaShareDialog').waitFor();assert.equal(await p.getByRole('button',{name:'画像としてコピー'}).count(),1);assert.equal(await p.getByRole('button',{name:'PDFとして保存'}).count(),1);await p.waitForFunction(()=>[...document.querySelectorAll('.qbMediaShareAction')].every(button=>!button.disabled));await p.locator('.qbMediaShareDialog').click({position:{x:2,y:2}});await p.locator('.qbMediaShareDialog').waitFor({state:'detached'});
 const converted=await p.evaluate(async()=>{const image=await QBMediaShare.output({source:'/fixture.pdf',kind:'pdf',page:2},'image'),pdf=await QBMediaShare.output({source:'/fixture.pdf',kind:'pdf'},'pdf'),bitmap=await createImageBitmap(image.blob),canvas=document.createElement('canvas');canvas.width=bitmap.width;canvas.height=bitmap.height;canvas.getContext('2d').drawImage(bitmap,0,0);return{imageType:image.blob.type,pdfType:pdf.blob.type,pages:(await (await import('./vendor/pdfjs/pdf-lib.mjs')).PDFDocument.load(await pdf.blob.arrayBuffer())).getPageCount(),pixel:[...canvas.getContext('2d').getImageData(10,10,1,1).data]}});assert.deepEqual(converted,{imageType:'image/png',pdfType:'application/pdf',pages:3,pixel:[0,255,0,255]});
 assert.ok(await p.locator('.qbPdfPoster canvas').first().evaluate(c=>c.width>=parseFloat(c.style.width)*1.9));
 assert.ok(await p.locator('[data-inline-page]').evaluateAll(nodes=>nodes.every(n=>{const r=n.getBoundingClientRect();return r.width<=380.5&&r.height<=400.5})));
 assert.equal(await p.locator('[data-inline-page]').evaluateAll(nodes=>Math.round(nodes[0].getBoundingClientRect().top)===Math.round(nodes[1].getBoundingClientRect().top)),true);
 assert.equal(await p.locator('#files img').count(),0);await p.locator('[data-inline-page="1"]').click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');
 const waitForWholePage=()=>p.waitForFunction(()=>{const c=document.querySelector('.qbPdfPage')?.getBoundingClientRect(),s=document.querySelector('.qbPdfViewingStage')?.getBoundingClientRect();return c&&s&&c.left>=s.left+23&&c.right<=s.right-23&&c.top>=s.top+23&&c.bottom<=s.bottom-23});
 await waitForWholePage();await p.setViewportSize({width:390,height:700});await waitForWholePage();await p.screenshot({path:'test-results/ui/pdf-popup-fit-'+label+'.png'});
 // Pinch zoom changes only the PDF; the remaining single finger must not pan or navigate.
 const gesture=await p.evaluate(()=>{
  const stage=document.querySelector('.qbPdfViewingStage'),c=stage.querySelector('canvas'),r=c.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;
  const send=(type,id,x,y)=>stage.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerId:id,pointerType:'touch',clientX:x,clientY:y,button:0}));
  send('pointerdown',41,x-20,y);send('pointerdown',42,x+20,y);send('pointermove',41,x-80,y);send('pointermove',42,x+80,y);
  const expanded=c.getBoundingClientRect().width;send('pointerup',42,x+80,y);const before=stage.scrollLeft;send('pointermove',41,x-110,y);const after=stage.scrollLeft;send('pointerup',41,x-110,y);
  return {initial:r.width,expanded,before,after};
 });
 assert.ok(gesture.expanded>gesture.initial*3);assert.equal(gesture.after,gesture.before);
 await p.waitForTimeout(300);assert.ok(await p.locator('.qbPdfPage').evaluate(c=>c.getBoundingClientRect().width)>gesture.initial*3);
 const oneFingerPan=await p.locator('.qbPdfViewingStage').evaluate(stage=>{const r=stage.getBoundingClientRect(),x=r.left+r.width*.7,y=r.top+r.height/2,before=stage.scrollLeft;for(const [type,px] of [['pointerdown',x],['pointermove',x-130],['pointerup',x-130]])stage.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerId:55,pointerType:'touch',clientX:px,clientY:y,button:0}));return{before,after:stage.scrollLeft}});
 assert.ok(oneFingerPan.after>oneFingerPan.before);assert.equal(await p.locator('.qbPdfStatus').textContent(),'1 / 3ページ');
 await p.getByRole('button',{name:'全体を表示',exact:true}).click();await waitForWholePage();
 await p.locator('.qbPdfViewingStage').evaluate(stage=>{const r=stage.getBoundingClientRect(),x=r.left+r.width*.7,y=r.top+r.height/2;for(const [type,px] of [['pointerdown',x],['pointermove',x-130],['pointerup',x-130]])stage.dispatchEvent(new PointerEvent(type,{bubbles:true,cancelable:true,pointerId:56,pointerType:'touch',clientX:px,clientY:y,button:0}))});
 await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='2 / 3ページ');await p.getByRole('button',{name:'前のページ',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');
 assert.equal(await p.locator('#origin').evaluate(n=>n.inert),true);
 const color=async()=>{const handle=await p.waitForFunction(()=>{const c=document.querySelector('.qbPdfPage');if(!c||c.width<=10||c.height<=10)return false;const pixel=Array.from(c.getContext('2d').getImageData(10,10,1,1).data);return pixel[3]===255&&pixel});return handle.jsonValue()};
 assert.deepEqual(await color(),[255,0,0,255]);await p.getByRole('button',{name:'2ページを表示',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='2 / 3ページ');assert.deepEqual(await color(),[0,255,0,255]);
 await p.getByRole('button',{name:'＋',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='2 / 3ページ');assert.deepEqual(await color(),[0,255,0,255]);await p.waitForFunction(()=>document.querySelectorAll('.qbPdfPageStrip canvas').length===3);await p.getByRole('button',{name:'全体を表示',exact:true}).click();await waitForWholePage();
 await p.getByRole('button',{name:'閉じる',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});assert.equal(await p.locator('#origin').evaluate(n=>n.inert),false);
 // Page numbers in the enlarged viewer can be dragged; the PDF editor receives
 // the original page and the complete pending order instead of saving silently.
 await p.evaluate(()=>{window.dragEdit=null;document.querySelector('#files').qbEditMedia=async(page,order)=>{window.dragEdit={page,order};return null}});
 await p.locator('[data-inline-page="1"]').click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');
 const dragFrom=await p.getByRole('button',{name:'1ページを表示',exact:true}).boundingBox(),dragTo=await p.getByRole('button',{name:'3ページを表示',exact:true}).boundingBox();
 await p.mouse.move(dragFrom.x+dragFrom.width/2,dragFrom.y+dragFrom.height/2);await p.mouse.down();await p.mouse.move(dragTo.x+dragTo.width/2,dragTo.y+dragTo.height/2,{steps:8});await p.mouse.up();
 await p.waitForFunction(()=>window.dragEdit);assert.deepEqual(await p.evaluate(()=>dragEdit),{page:1,order:[1,2,0]});await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');await p.getByRole('button',{name:'閉じる',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});
 await p.setViewportSize({width:1024,height:800});
 await p.addScriptTag({url:url+'image-viewer.js'});
 await p.evaluate(()=>{const files=document.querySelector('#files');files.className='qbMediaHostV2';const c=document.createElement('canvas');c.width=100;c.height=100;c.getContext('2d').fillRect(0,0,100,100);for(const where of ['prepend','append']){const img=document.createElement('img');img.className='qbMediaImg';img.src=c.toDataURL();img.alt=where;files[where](img)}document.body.insertAdjacentHTML('beforeend',`<div id="view"><div class="card"><div class="qtext">拡大中に確認する問題文</div><div class="qsiHost"><div class="qsiGrid"><div class="qsiImgWrap"><img class="qsiImg" alt="問題画像" src="${c.toDataURL()}"></div></div></div></div></div>`);window.qbGetScreen=()=> 'practice';window.qbResolveCurrentQuestion=()=>({id:'q1',stem:'拡大中に確認する問題文',explanation_overview:'この問題のポイント',choices:[{choice_key:'A',choice_text:'誤答',explanation:'Aの解説'},{choice_key:'B',choice_text:'正答',explanation:'Bの解説'}],ans:[1]})});
 await p.evaluate(()=>{const article=document.createElement('article'),button=document.createElement('button'),img=document.createElement('img');article.className='qbLibraryItem';button.className='qbLibraryImageButton';img.src=document.querySelector('.qbMediaImg').src;img.alt='ライブラリ画像';button.append(img);article.append(button);document.body.append(article)});await p.waitForFunction(()=>document.querySelector('.qbLibraryItem>.qbMediaShareButton'));
 assert.equal(await p.locator('[data-inline-page]').count(),3);
 await p.locator('[data-inline-page="2"]').click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='2 / 3ページ');
 await p.locator('.qbPdfShare').click();await p.locator('.qbMediaShareDialog').waitFor();assert.match(await p.locator('.qbMediaShareHint').textContent(),/表示中の2ページ/);await p.locator('.qbMediaShareDialog').click({position:{x:2,y:2}});await p.locator('.qbMediaShareDialog').waitFor({state:'detached'});assert.equal(await p.locator('.qbPdfModal').count(),1);
 await p.getByRole('button',{name:'問題を確認',exact:true}).click();const pdfQuestion=p.getByRole('region',{name:'問題のプレビュー',exact:true});assert.match(await pdfQuestion.textContent(),/拡大中に確認する問題文/);assert.equal(await pdfQuestion.getByRole('img',{name:'問題画像',exact:true}).count(),1);assert.deepEqual(await pdfQuestion.getByRole('list',{name:'選択肢',exact:true}).getByRole('listitem').allTextContents(),['A誤答','B正答']);await pdfQuestion.getByRole('tab',{name:'解答',exact:true}).click();assert.match(await pdfQuestion.textContent(),/B 正答/);assert.match(await pdfQuestion.textContent(),/この問題のポイント/);assert.match(await pdfQuestion.textContent(),/Bの解説/);await pdfQuestion.getByRole('tab',{name:'問題',exact:true}).click();assert.match(await pdfQuestion.textContent(),/拡大中に確認する問題文/);await p.keyboard.press('Escape');assert.equal(await pdfQuestion.isHidden(),true);assert.equal(await p.locator('.qbPdfModal').count(),1);
 const wheel=await p.locator('.qbPdfViewingStage').evaluate(stage=>{const c=stage.querySelector('canvas'),r=c.getBoundingClientRect(),panel=stage.closest('.qbPdfPanel').getBoundingClientRect();const e=new WheelEvent('wheel',{bubbles:true,cancelable:true,ctrlKey:true,deltaY:-150,clientX:r.left+r.width/2,clientY:r.top+r.height/2});stage.dispatchEvent(e);return{prevented:e.defaultPrevented,ratio:c.getBoundingClientRect().width/r.width,stable:stage.closest('.qbPdfPanel').getBoundingClientRect().width===panel.width}});assert.ok(wheel.prevented&&wheel.ratio>1.5&&wheel.stable);
 await p.getByRole('button',{name:'次のページ',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='3 / 3ページ');await p.getByRole('button',{name:'次のページ',exact:true}).click();await p.locator('.qbImageLightbox').waitFor();assert.equal(await p.locator('.qbImageLightboxStage img').getAttribute('alt'),'append');
 await p.locator('.qbImageLightboxShare').click();await p.locator('.qbMediaShareDialog').waitFor();await p.locator('.qbMediaShareDialog').click({position:{x:2,y:2}});await p.locator('.qbMediaShareDialog').waitFor({state:'detached'});assert.equal(await p.locator('.qbImageLightbox').count(),1);
 await p.getByRole('button',{name:'問題を確認',exact:true}).click();const imageQuestion=p.getByRole('region',{name:'問題のプレビュー',exact:true});assert.match(await imageQuestion.textContent(),/拡大中に確認する問題文/);assert.equal(await imageQuestion.getByRole('img',{name:'問題画像',exact:true}).count(),1);assert.deepEqual(await imageQuestion.getByRole('list',{name:'選択肢',exact:true}).getByRole('listitem').allTextContents(),['A誤答','B正答']);await imageQuestion.getByRole('button',{name:'閉じる',exact:true}).click();assert.equal(await p.locator('.qbImageLightbox').count(),1);
 await p.getByRole('button',{name:'前の画像',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='3 / 3ページ');
 await p.getByRole('button',{name:'1ページを表示',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');await p.getByRole('button',{name:'前のページ',exact:true}).click();await p.locator('.qbImageLightbox').waitFor();assert.equal(await p.locator('.qbImageLightboxStage img').getAttribute('alt'),'prepend');await p.getByRole('button',{name:'次の画像',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');await p.getByRole('button',{name:'閉じる',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});
 await p.locator('.qbMediaImg').first().dispatchEvent('pointerdown',{pointerId:91,pointerType:'touch',button:0,isPrimary:true,clientX:30,clientY:30});await p.waitForTimeout(560);await p.locator('.qbMediaShareDialog').waitFor();await p.locator('.qbMediaShareDialog').click({position:{x:2,y:2}});await p.locator('.qbMediaShareDialog').waitFor({state:'detached'});
 const imagePdf=await p.evaluate(async()=>{const source=document.querySelector('.qbMediaImg').src,result=await QBMediaShare.output({source,kind:'image'},'pdf'),doc=await (await import('./vendor/pdfjs/pdf-lib.mjs')).PDFDocument.load(await result.blob.arrayBuffer());return{type:result.blob.type,pages:doc.getPageCount()}});assert.deepEqual(imagePdf,{type:'application/pdf',pages:1});
 await p.evaluate(async()=>{const blob=await (await fetch('/fixture.pdf')).blob();window.sourcePDF=blob;window.pageImage=undefined;QBFiles.open(blob,{pickPage:true}).then(b=>window.pageImage=b)});await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');await p.getByRole('button',{name:'3ページを表示',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='3 / 3ページ');await p.getByRole('button',{name:'このページを画像として追加',exact:true}).click();await p.waitForFunction(()=>window.pageImage instanceof Blob);
 const exported=await p.evaluate(async()=>{const b=await createImageBitmap(pageImage),c=document.createElement('canvas');c.width=b.width;c.height=b.height;const x=c.getContext('2d');x.drawImage(b,0,0);return{type:pageImage.type,w:b.width,h:b.height,pixel:[...x.getImageData(10,10,1,1).data],source:await sourcePDF.text()}});assert.equal(exported.type,'image/png');assert.deepEqual(exported.pixel,[0,0,255,255]);assert.equal(exported.source,fixture.toString());
 const paste=await p.evaluate(async()=>{const d=new DataTransfer();d.items.add(new File([sourcePDF],'test.pdf',{type:'application/pdf'}));d.items.add(new File(['image'],'x.png',{type:'image/png'}));d.setData('text/plain','keep text');const e=new ClipboardEvent('paste',{clipboardData:d});const files=QBFiles.filesFromPaste(e);let rejected=false;try{await QBFiles.validate(new File(['not PDF'],'fake.pdf',{type:'application/pdf'}))}catch{rejected=true}return {types:files.map(f=>f.type),prevented:e.defaultPrevented,rejected}});assert.deepEqual(paste,{types:['application/pdf','image/png'],prevented:false,rejected:true});
 await p.evaluate(()=>{const host=document.createElement('div');host.className='qbLibraryImageButton';host.id='pdfCoverTest';host.style.width='220px';host.innerHTML=QBFiles.markup('/fixture.pdf');document.body.append(host)});await p.locator('#pdfCoverTest').scrollIntoViewIfNeeded();await p.waitForFunction(()=>document.querySelector('#pdfCoverTest [data-pdf-pages="3"]'));assert.equal(await p.locator('#pdfCoverTest .qbPdfCard').evaluate(n=>n.getBoundingClientRect().height),150);assert.ok(await p.locator('#pdfCoverTest .qbPdfCard').evaluate(n=>n.getBoundingClientRect().width<=220));await p.locator('#pdfCoverTest').evaluate(n=>n.remove());
 // A missing MIME type still identifies PDF by filename; rendered replacements update in place.
 assert.equal(await p.evaluate(()=>QBFiles.filesFromPaste({clipboardData:{files:[new File(['%PDF-'],'copied.PDF')]}}).length),1);
 await p.evaluate(()=>{window.previewNode=document.createElement('img');document.querySelector('#files').append(previewNode);QBFiles.present(previewNode,'/fixture.pdf');QBFiles.present(previewNode,'/fixture.pdf?v=edited')});
 await p.locator('[data-pdf-src="/fixture.pdf?v=edited"]').scrollIntoViewIfNeeded();
 await p.waitForFunction(()=>document.querySelector('[data-pdf-src="/fixture.pdf?v=edited"][data-pdf-pages="3"]'));
 assert.equal(await p.locator('[data-pdf-src="/fixture.pdf?v=edited"]').count(),1);
 // A network retry must keep the original page-selection promise alive.
 let attempts=0;await p.route('**/retry.pdf',r=>{attempts++;return attempts===1?r.fulfill({status:503,body:'unavailable'}):r.fulfill({contentType:'application/pdf',body:fixture})});
 await p.evaluate(()=>{window.retryImage=undefined;QBFiles.open('/retry.pdf',{pickPage:true}).then(b=>window.retryImage=b)});await p.getByRole('button',{name:'再試行',exact:true}).waitFor();assert.equal(await p.evaluate(()=>retryImage===undefined),true);await p.getByRole('button',{name:'再試行',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');await p.getByRole('button',{name:'このページを画像として追加',exact:true}).click();await p.waitForFunction(()=>window.retryImage instanceof Blob);
 // The production sorter persists one common order for image and PDF attachments.
 await p.evaluate(()=>{
   const pdf=QBFiles.markup('/fixture.pdf'),img='<img alt="image" src="data:image/png;base64,iVBORw0KGgo=">';
   document.querySelector('#files').innerHTML=`<div class="qbMediaHostV2"><div class="qbPublicImageWrap" data-row="pub-image" data-placement="explanation_overview">${img}<div class="qbImageWriteActions"></div></div><div class="qbPublicImageWrap" data-row="pub-pdf">${pdf}<div class="qbImageWriteActions"></div></div></div><div class="adeEditor" data-ade-editor="overview"><div class="oeiGrid"><div class="oeiItem" data-id="edit-image">${img}<div class="oeiItemActions"></div></div><div class="oeiItem" data-id="edit-pdf">${pdf}<div class="oeiItemActions"></div></div></div></div><div class="qsiGrid"><div class="qsiImgWrap" data-row="stem-image">${img}</div><div class="qsiImgWrap" data-row="stem-pdf">${pdf}</div></div><div class="qbPersonal" data-note-key="explanation_overview|"><div class="qbNoteImageGrid"><div class="qbNoteImageWrap" data-row="note-image"><img src="/storage/v1/object/sign/user-note-images/note.png"></div><div class="qbNoteImageWrap" data-row="note-pdf">${QBFiles.markup('/storage/v1/object/sign/user-note-images/note.pdf')}</div></div></div>`;
   window.sorts=[];window.writes=[];window.authorized=[];window.pq=()=>({id:'question-1'});window.Sortable=class{constructor(el,options){sorts.push({el,options})}};
   class Query{constructor(table){this.table=table;this.filters={}}select(){return this}eq(k,v){this.filters[k]=v;return this}is(){return this}order(){return this}limit(){return this}update(v){this.patch=v;return this}maybeSingle(){if(this.patch){writes.push({table:this.table,patch:this.patch,filters:this.filters});return Promise.resolve({data:{id:this.filters.id}})}return Promise.resolve({data:this.table==='profiles'?{role:'admin'}:{id:'note-1'}})}then(a,b){return Promise.resolve({data:[{id:'note-image',image_path:'note.png'},{id:'note-pdf',image_path:'note.pdf'}]}).then(a,b)}}
   window.qbSupabase={auth:{getUser:async()=>({data:{user:{id:'user-1'}}})},from:t=>new Query(t)};
   document.querySelector('.qbPersonal').qbImageContext=()=>({sb:qbSupabase,questionId:'question-1',userId:'user-1'});window.QBImageStore={authorize:async c=>authorized.push(c.questionId)};
 });
 await p.addScriptTag({url:url+'image-sortable-v1.js'});await p.waitForFunction(()=>sorts.length===4);
 await p.evaluate(async()=>{for(const {el,options} of sorts){el.prepend(el.children[1]);await options.onEnd()}});
 const saved=await p.evaluate(()=>writes);assert.equal(saved.length,8);for(let i=0;i<8;i+=2){assert.match(saved[i].filters.id,/-pdf$/);assert.equal(saved[i].patch.sort_order,10);assert.match(saved[i+1].filters.id,/-image$/);assert.equal(saved[i+1].patch.sort_order,20);assert.equal(saved[i].filters.question_id,'question-1');assert.deepEqual(Object.keys(saved[i].patch),['sort_order'])}assert.equal(saved.find(r=>r.filters.id==='note-pdf').filters.user_id,'user-1');
 fs.mkdirSync(path.join(root,'test-results/ui'),{recursive:true});await p.screenshot({path:path.join(root,`test-results/ui/${label}-file-card.png`)});
 assert.deepEqual(errors,[]);await p.close();console.log(label+' PASS stable inline PDF while scrolling, export/share, long press, page navigation, bounded thumbnails, zoom, explicit PNG extraction, paste types, retry and mixed attachment sorting');
}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));try{for(const [label,type] of [['Chromium',chromium],['WebKit',webkit]]){const b=await type.launch();try{await run(b,label,`http://127.0.0.1:${server.address().port}/`)}finally{await b.close()}}}finally{server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
