'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium,webkit}=require('playwright'),{boot}=require('./image-library.browser.cjs');
const read=f=>fs.readFileSync(path.join(__dirname,'..',f),'utf8');
async function run(browser,label){
 const {page:p,errors}=await boot(browser);p.setDefaultTimeout(10000);await p.setViewportSize({width:1100,height:1000});
 await p.locator('.qbLibraryEntry').click();await p.locator('.qbLibraryImageButton').first().waitFor();await p.evaluate(()=>db.qb_image_library_items[0].updated_at='2026-09-10T14:23:00Z');await p.locator('.qbLibraryImageButton').first().click();assert.equal(await p.locator('.qbLibraryUpdated').textContent(),'最終更新：2026/09/10 23:23（日本時間）');
 await p.addStyleTag({content:read('image-annotation-v1.css')});await p.addScriptTag({content:read('image-annotation-model-v1.js')});await p.evaluate(()=>{const H=QBImageModel.History;QBImageModel.History=class extends H{constructor(s){super(s);if(s.items)window.sceneHistory=this}}});await p.addScriptTag({content:read('image-annotation-editor-v1.js')});
 await p.evaluate(()=>{localStorage.setItem('qb-image-editor-settings-v1','{}');const c=document.createElement('canvas');c.width=800;c.height=600;const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,800,600);window.pq=()=>({id:'test'});window.QBQuestionExport={render:async()=>({blob:await new Promise(r=>c.toBlob(r))})};QBImageEditor.open(c.toDataURL(),{onSave:async blob=>{window.savedCounterSize=blob.size;const im=await createImageBitmap(blob);const out=document.createElement('canvas');out.width=800;out.height=600;out.getContext('2d').drawImage(im,0,0);window.savedCounterPixel=[...out.getContext('2d').getImageData(85,100,1,1).data]}})});
 await p.locator('.qbDrawSave:enabled').waitFor();await p.getByRole('button',{name:'連番',exact:true}).click();await p.getByRole('button',{name:'全体表示',exact:true}).click();
 assert.equal(await p.getByLabel('連番の種類').inputValue(),'letter');await p.getByLabel('連番の種類').selectOption('number');
 const box=await p.locator('.qbDrawStage').boundingBox(),z=Math.min((box.width-32)/800,(box.height-32)/600),at=(x,y)=>({x:box.x+(box.width-800*z)/2+x*z,y:box.y+(box.height-600*z)/2+y*z});
 const click=async(x,y)=>{const a=at(x,y);await p.mouse.click(a.x,a.y)};const labels=()=>p.evaluate(()=>sceneHistory.current.items.map(i=>i.label));
 await click(100,100);await click(250,100);assert.deepEqual(await labels(),['1','2']);await p.keyboard.press('Meta+z');assert.deepEqual(await labels(),['1']);await p.keyboard.press('Meta+Shift+z');assert.deepEqual(await labels(),['1','2']);await p.keyboard.press('Control+z');await click(250,100);assert.deepEqual(await labels(),['1','2']);
 await p.getByLabel('連番の種類').selectOption('letter');await p.getByLabel('次に貼る番号').fill('z');await p.getByLabel('次に貼る番号').press('Tab');await click(400,100);await click(550,100);assert.deepEqual(await labels(),['1','2','z','aa']);
 await p.getByLabel('ステッカーの大きさ').selectOption('96');await p.getByRole('button',{name:'青',exact:true}).click();await click(650,350);assert.equal(await p.evaluate(()=>sceneHistory.current.items.at(-1).w),96);assert.equal(await p.evaluate(()=>sceneHistory.current.items.at(-1).color),'#2463d3');
 await p.locator('[data-tool=lasso]').click();const a=at(650,350),b=at(550,350);await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(b.x,b.y,{steps:5});await p.mouse.up();assert.equal((await labels()).length,5);await p.keyboard.press('Backspace');assert.equal((await labels()).length,4);await p.keyboard.press('Meta+z');assert.equal((await labels()).length,5);
 await p.getByRole('button',{name:'連番',exact:true}).click();
 // Touch tap adds a counter even when finger ink is off; a drag does not.
 const touch=async(type,id,x,y)=>{const q=at(x,y);await p.locator('.qbDrawCanvas').dispatchEvent(type,{pointerId:id,pointerType:'touch',clientX:q.x,clientY:q.y,button:0,bubbles:true})};
 await touch('pointerdown',40,200,400);await touch('pointerup',40,200,400);assert.equal((await labels()).length,6);await touch('pointerdown',41,350,450);await touch('pointermove',41,390,450);await touch('pointerup',41,390,450);assert.equal((await labels()).length,6);
 await touch('pointerdown',42,300,400);await touch('pointerdown',43,450,400);await touch('pointerup',42,300,400);await touch('pointerup',43,450,400);assert.equal((await labels()).length,6);
 await p.getByRole('button',{name:'問題・解答を表示',exact:true}).click();const view=p.locator('.qbDrawReferenceViewport');await view.waitFor();await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));const canvasBefore=await p.locator('.qbDrawCanvas').screenshot();const refImage=view.locator('img');await p.locator('.qbDrawReferenceControls').getByRole('button',{name:'＋',exact:true}).click();assert.equal(await view.getAttribute('data-scale'),'1.25');
 const transform=await refImage.evaluate(n=>n.style.transform),r=await view.boundingBox();await p.mouse.move(r.x+30,r.y+40);await p.mouse.down();await p.mouse.move(r.x+80,r.y+90);await p.mouse.up();assert.notEqual(await refImage.evaluate(n=>n.style.transform),transform);
 await view.dispatchEvent('wheel',{ctrlKey:true,deltaY:-100,clientX:r.x+50,clientY:r.y+50,bubbles:true,cancelable:true});assert.ok(Number(await view.getAttribute('data-scale'))>1.25);assert.equal((await labels()).length,6);
 const referenceTouch=async(type,id,x,y)=>view.dispatchEvent(type,{pointerId:id,pointerType:'touch',clientX:r.x+x,clientY:r.y+y,button:0,bubbles:true});const scaleBefore=Number(await view.getAttribute('data-scale'));await referenceTouch('pointerdown',50,40,60);await referenceTouch('pointerdown',51,120,60);await referenceTouch('pointermove',51,180,60);await referenceTouch('pointerup',50,40,60);await referenceTouch('pointerup',51,180,60);assert.ok(Number(await view.getAttribute('data-scale'))>scaleBefore);assert.deepEqual(await p.locator('.qbDrawCanvas').screenshot(),canvasBefore);
 await p.locator('.qbDrawReferenceControls').getByRole('button',{name:'全体表示',exact:true}).click();assert.equal(await view.getAttribute('data-scale'),'1');
 await p.locator('.qbDrawSave').click();await p.locator('.qbDrawModal').waitFor({state:'detached'});assert.ok(await p.evaluate(()=>savedCounterSize>100));assert.notDeepEqual(await p.evaluate(()=>savedCounterPixel.slice(0,3)),[255,255,255]);assert.deepEqual(errors,[]);await p.close();console.log(label+' PASS counters, alphabet, start, size/color, undo/redo, move/delete, touch/pinch safety, export, independent reference and timestamp');
}
(async()=>{for(const [label,type] of [['Chromium',chromium],['WebKit',webkit]]){const b=await type.launch();try{await run(b,label)}finally{await b.close()}}})().catch(e=>{console.error(e);process.exitCode=1});
