'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {chromium,webkit}=require('playwright');const root=path.resolve(__dirname,'..');
async function run(browser,label){
 const p=await browser.newPage({viewport:{width:1024,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(20000);await p.route('**/*',r=>r.request().url().startsWith('blob:')?r.continue():r.fulfill({contentType:'text/html',body:'<!doctype html><body><button>背景</button></body>'}));await p.goto('https://crop.test/');
 await p.addStyleTag({path:path.join(root,'image-annotation-v1.css')});await p.addStyleTag({path:require.resolve('cropperjs/dist/cropper.css')});await p.evaluate(()=>document.head.lastElementChild.id='cropperCss');await p.addScriptTag({path:require.resolve('cropperjs/dist/cropper.js')});
 for(const f of ['image-annotation-model-v1.js','image-crop-editor-v1.js'])await p.addScriptTag({path:path.join(root,f)});
 await p.evaluate(()=>{const H=QBImageModel.History;QBImageModel.History=class extends H{constructor(s){super(s);window.historyScene=this}}});await p.addScriptTag({path:path.join(root,'image-annotation-editor-v1.js')});
 await p.evaluate(()=>{const c=document.createElement('canvas');c.width=1000;c.height=600;const x=c.getContext('2d');x.fillStyle='red';x.fillRect(0,0,1000,600);window.base=c.toDataURL();window.saved=null;QBImageEditor.open(base).then(b=>window.saved=b)});await p.locator('.qbDrawSave:enabled').waitFor();assert.equal(await p.locator('.qbDrawCropSelected:visible').count(),0);
 await p.evaluate(async()=>{const c=document.createElement('canvas');c.width=600;c.height=300;c.getContext('2d').fillRect(0,0,600,300);const b=await new Promise(r=>c.toBlob(r)),d=new DataTransfer();d.items.add(new File([b],'extra.png',{type:'image/png'}));document.querySelector('.qbDrawCanvas').dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}))});await p.waitForFunction(()=>historyScene.current.items.length===1);const original=await p.evaluate(()=>structuredClone(historyScene.current));
 await p.locator('.qbDrawCropAll').click();await p.locator('.qbCropSave:enabled').waitFor();assert.equal(await p.locator('#qbCropTitle').textContent(),'画像全体をトリミング');assert.equal(await p.locator('.qbDrawPanel').evaluate(n=>n.inert),true);await p.evaluate(()=>document.querySelector('.qbCropImage').cropper.setData({x:100,y:50,width:800,height:500}));await p.locator('.qbCropSave').click();await p.locator('.qbCropModal').waitFor({state:'detached'});
 let scene=await p.evaluate(()=>historyScene.current);assert.equal(scene.width,800);assert.equal(scene.base.x,-100);assert.equal(scene.items[0].x,original.items[0].x-100);assert.equal(scene.items[0].assetId,original.items[0].assetId);
 await p.getByRole('button',{name:'↶ 元に戻す',exact:true}).click();assert.deepEqual(await p.evaluate(()=>historyScene.current),original);await p.getByRole('button',{name:'↷ やり直す',exact:true}).click();assert.equal(await p.evaluate(()=>historyScene.current.width),800);await p.getByRole('button',{name:'↶ 元に戻す',exact:true}).click();
 // Re-select the image with the lasso tool and crop only its source rectangle.
 await p.getByRole('button',{name:'投げ縄',exact:true}).click();await p.locator('.qbDrawNavigation').getByRole('button',{name:'全体表示',exact:true}).click();const box=await p.locator('.qbDrawStage').boundingBox(),z=Math.min((box.width-32)/1000,(box.height-32)/600);await p.mouse.click(box.x+box.width/2,box.y+box.height/2);await p.locator('.qbDrawCropSelected:visible').waitFor();
 await p.locator('.qbDrawCropSelected').click();await p.locator('.qbCropSave:enabled').waitFor();await p.evaluate(()=>document.querySelector('.qbCropImage').cropper.setData({x:100,y:0,width:300,height:300}));await p.locator('.qbCropSave').click();await p.locator('.qbCropModal').waitFor({state:'detached'});scene=await p.evaluate(()=>historyScene.current);assert.equal(scene.width,1000);assert.equal(scene.items[0].sourceRect.w,300);assert.equal(scene.items[0].w,300);assert.equal(scene.items[0].assetId,original.items[0].assetId);await p.getByRole('button',{name:'↶ 元に戻す',exact:true}).click();assert.deepEqual(await p.evaluate(()=>historyScene.current),original);
 await p.locator('.qbDrawSave').click();await p.waitForFunction(()=>saved instanceof Blob);assert.equal(await p.evaluate(()=>saved.type),'image/png');
 // Standalone crop must use tiles even if giant canvas APIs are unusable.
 await p.evaluate(()=>{Cropper.prototype.getCroppedCanvas=()=>{throw Error('full canvas forbidden')};window.cropped=null;QBImageCrop.open(base).then(b=>window.cropped=b)});await p.locator('.qbCropSave:enabled').waitFor();await p.locator('[data-rotate="90"]').click();await p.locator('.qbCropFull').click();await p.locator('.qbCropSave').click();await p.waitForFunction(()=>cropped instanceof Blob);const result=await p.evaluate(async()=>{const im=await createImageBitmap(cropped),c=document.createElement('canvas');c.width=im.width;c.height=im.height;const x=c.getContext('2d');x.drawImage(im,0,0);return {w:im.width,h:im.height,pixel:[...x.getImageData(200,200,1,1).data]}});assert.deepEqual(result,{w:600,h:1000,pixel:[255,0,0,255]});assert.deepEqual(errors,[]);await p.close();console.log(label+' PASS full/selected crop separation, unsaved source retention, undo/redo, rotated tile export without full canvas');
}
(async()=>{for(const [label,type] of [['Chromium',chromium],['WebKit',webkit]]){const b=await type.launch();try{await run(b,label)}finally{await b.close()}}})().catch(e=>{console.error(e);process.exitCode=1});
