'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium,webkit}=require('playwright');const {boot}=require('./image-library.browser.cjs');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8');
async function run(browser,label){
 const {page:p,errors}=await boot(browser);let n=0;const pass=x=>console.log(label+' '+(++n)+' '+x);await p.route('blob:**',r=>r.continue());p.on('pageerror',e=>console.log('PAGE ERROR',e.message));
 await p.evaluate(async()=>{const c=document.createElement('canvas');c.width=300;c.height=200;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,300,200);x.fillStyle='black';x.fillText('Original image',20,30);const blob=await new Promise(r=>c.toBlob(r));db.qb_image_library_items.forEach(i=>objects.set('qb-image-library/'+i.object_path,blob));window.backgroundSave=0;addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='s')backgroundSave++});db.qb_image_library_catalog.push({id:'u1',kind:'unit',parent_id:'s1',name:'眼球運動',path:'眼科学 / 眼球運動',subject_id:'s1',sort_order:10,revision:1,aliases:[]})});
 await p.locator('.qbLibraryEntry').click();await p.locator('.qbLibraryImageButton').first().click();await p.getByLabel('画像名',{exact:true}).fill('⌘Sで更新');await p.getByLabel('語呂合わせ',{exact:true}).check();await p.getByLabel('眼科学 / 眼球運動',{exact:true}).check();
 await p.getByLabel('画像名',{exact:true}).focus();await p.keyboard.press('Meta+s');await p.waitForFunction(()=>db.qb_image_library_items[0].revision===2);assert.equal(await p.locator('.qbLibraryOverlay').count(),1);assert.equal(await p.getByLabel('画像名',{exact:true}).inputValue(),'⌘Sで更新');assert.equal(await p.evaluate(()=>backgroundSave),0);
 assert.deepEqual(await p.evaluate(()=>db.qb_image_library_items[0].metadata.unit_ids),['u1']);assert.ok(await p.evaluate(()=>db.qb_image_library_items[0].metadata.roles.includes('語呂合わせ')));
 await p.getByLabel('補足・学習意図',{exact:true}).fill('Ctrl Sも使える');await p.keyboard.press('Control+s');await p.waitForFunction(()=>db.qb_image_library_items[0].revision===3);await p.keyboard.press('Control+s');assert.equal(await p.evaluate(()=>db.qb_image_library_items[0].revision),3);pass('Cmd/Ctrl S saves metadata in place, isolated from question, with mnemonic and units');
 // Production annotation and crop editors, no mock image editing.
 await p.addScriptTag({content:read('image-annotation-model-v1.js')});await p.addStyleTag({content:read('image-annotation-v1.css')});await p.addScriptTag({content:read('image-annotation-editor-v1.js')});
 await p.addScriptTag({content:fs.readFileSync(require.resolve('cropperjs/dist/cropper.js'),'utf8')});await p.addStyleTag({content:fs.readFileSync(require.resolve('cropperjs/dist/cropper.css'),'utf8')});await p.addScriptTag({content:read('image-crop-editor-v1.js')});
 await p.getByRole('button',{name:'書き込み',exact:true}).click();await p.locator('.qbDrawCanvas').waitFor();await p.waitForFunction(()=>!document.querySelector('.qbDrawSave').disabled);
 assert.ok(await p.locator('.qbDrawModal').evaluate(el=>Number(getComputedStyle(el).zIndex)>Number(getComputedStyle(document.querySelector('.qbLibraryOverlay')).zIndex)));
 await p.keyboard.press('Control+s');await p.locator('.qbDrawModal').waitFor({state:'detached'});await p.waitForFunction(()=>db.qb_image_library_items[0].image_version===2);assert.equal(await p.evaluate(()=>db.qb_image_library_items[0].original_path),'i1/original.png');
 await p.waitForFunction(()=>!document.querySelector('.qbLibraryPanel').inert&&!document.querySelector('.qbLibraryBody > div:last-child').inert);await p.getByRole('button',{name:'トリミング',exact:true}).click();await p.locator('.qbCropSave:enabled').waitFor({timeout:10000}).catch(async e=>{console.log('CROP DIAGNOSTIC',await p.evaluate(()=>({hasModal:!!document.querySelector('.qbCropModal'),status:document.querySelector('.qbCropStatus')?.textContent,library:document.querySelector('.qbLibraryBody')?.textContent.slice(0,1200),panelInert:document.querySelector('.qbLibraryPanel')?.inert})));throw e});await p.locator('.qbCropSave').click();await p.waitForFunction(()=>db.qb_image_library_items[0].image_version===3);await p.getByRole('button',{name:'元画像に戻す',exact:true}).click();await p.waitForFunction(()=>db.qb_image_library_items[0].object_path==='i1/original.png');assert.equal(await p.evaluate(()=>objects.has('qb-image-library/i1/original.png')),true);pass('existing write/crop editors open above library and retain original and history');
 await p.getByRole('button',{name:'一覧へ戻る'}).click();await p.locator('.qbLibrarySelect input').nth(1).check();await p.locator('.qbLibrarySelect input').nth(0).check();await p.getByRole('button',{name:'選択した画像をセットにする'}).click();await p.getByLabel('セット名').fill('眼球運動セット');await p.keyboard.press('Meta+s');await p.waitForFunction(()=>db.qb_image_library_sets.length===1);assert.deepEqual(await p.evaluate(()=>db.qb_image_library_sets[0].image_ids),['i2','i1']);
 await p.getByRole('button',{name:'一覧へ戻る'}).click();await p.locator('.qbLibrarySet').waitFor();assert.equal(await p.locator('.qbLibraryItem').count(),1);const carousel=p.locator('.qbLibrarySet');assert.equal(await carousel.locator('.qbLibrarySlide').count(),2);await p.waitForFunction(()=>[...document.querySelectorAll('.qbLibrarySlide img')].every(i=>i.naturalWidth===300));await carousel.getByRole('button',{name:'次',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbLibrarySlideNav span').textContent==='2 / 2');assert.equal(await carousel.locator('.qbLibrarySlides').evaluate(el=>getComputedStyle(el).scrollSnapType),'x mandatory');pass('set appears once with ordered, horizontally scrollable thumbnails');
 await p.getByRole('button',{name:'閉じる',exact:true}).click();await p.locator('.qsiEditor .qbLibraryAction').click();await p.locator('.qbLibrarySet').waitFor();await p.locator('.qbLibrarySet').getByLabel('全部を選択').check();await p.getByRole('button',{name:'選択した画像を貼る'}).click();await p.locator('.qbLibraryOverlay').waitFor({state:'detached'});assert.deepEqual(await p.evaluate(()=>db.qb_image_library_usages.map(u=>u.image_id)),['i2','i1']);pass('whole set attaches independent copies in set order');
 await p.locator('.qsiEditor .qbLibraryAction').click();await p.locator('.qbLibrarySet').getByRole('button',{name:'一部を選ぶ・セットを編集'}).click();await p.locator('.qbLibrarySetMember').first().waitFor();await p.locator('.qbLibrarySetMember').nth(1).getByLabel('この画像を選択').check();await p.getByRole('button',{name:'選択した画像を貼る'}).click();await p.locator('.qbLibraryOverlay').waitFor({state:'detached'});assert.deepEqual(await p.evaluate(()=>db.qb_image_library_usages.map(u=>u.image_id)),['i2','i1','i1']);const paths=await p.evaluate(()=>db.question_images.map(i=>i.image_path));assert.equal(new Set(paths).size,3);pass('subset attaches only checked member with a fresh copy');
 await p.locator('.qbLibraryEntry').click();await p.locator('.qbLibrarySet').getByRole('button',{name:'一部を選ぶ・セットを編集'}).click();await p.locator('.qbLibrarySetMember').nth(1).getByRole('button',{name:'前へ',exact:true}).click();await p.getByRole('button',{name:'セットを保存',exact:true}).click();await p.waitForFunction(()=>db.qb_image_library_sets[0].image_ids[0]==='i1');assert.deepEqual(await p.evaluate(()=>db.question_images.map(i=>i.image_path)),paths);await p.getByRole('button',{name:'セットを解除',exact:true}).click();await p.locator('.qbLibraryImageButton').first().waitFor();assert.equal(await p.locator('.qbLibraryItem').count(),2);assert.equal(await p.evaluate(()=>db.question_images.length),3);pass('reorder and ungroup preserve members and all pasted copies');
 await p.getByLabel('複数枚を1セットとして追加',{exact:true}).check();await p.locator('.qbLibraryTools input[type=file][multiple]').setInputFiles([{name:'set-a.png',mimeType:'image/png',buffer:Buffer.from('a')},{name:'set-b.png',mimeType:'image/png',buffer:Buffer.from('b')}]);await p.waitForFunction(()=>db.qb_image_library_sets.length===2);assert.equal(await p.evaluate(()=>calls.filter(c=>c[1]==='qb_library_record_reading').length),0);pass('explicit multi-upload set creation requires no AI');
 await p.waitForFunction(()=>!document.querySelector('.qbLibraryBody > div').inert);await p.getByRole('button',{name:'科目・単元を管理',exact:true}).click();await p.getByLabel('編集対象',{exact:true}).selectOption('new-unit');await p.getByLabel('名称',{exact:true}).fill('検査');await p.getByLabel('所属する科目・上位単元',{exact:true}).selectOption('s1');await p.getByRole('spinbutton',{name:'並び順',exact:true}).fill('20');await p.keyboard.press('Meta+s');await p.waitForFunction(()=>db.qb_image_library_catalog.some(c=>c.name==='検査'));await p.getByRole('button',{name:'一覧へ戻る'}).click();await p.getByText('絞り込み',{exact:true}).click();assert.ok((await p.getByLabel('単元（下位も含む）',{exact:true}).textContent()).includes('眼科学 / 検査'));assert.equal(await p.evaluate(()=>db.subjects.length),2);pass('catalog manager adds ordered library units without changing problem subjects');
 assert.deepEqual(errors,[]);await p.close();console.log(label+' '+n+' set browser checks passed');
}
(async()=>{for(const [name,type] of [['Chromium',chromium],['WebKit',webkit]]){const b=await type.launch();try{await run(b,name)}finally{await b.close()}}})().catch(e=>{console.error(e);process.exitCode=1});
