'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium,webkit}=require('playwright'),root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://local').pathname;if(pathname==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head><meta charset="utf-8"><style>:root{--line:#ddd;--text:#172033;--muted:#667085;--accent:#16875f;--card:#fff}</style></head><body></body></html>');return}const file=path.resolve(root,'.'+decodeURIComponent(pathname));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return}try{res.setHeader('Content-Type','application/javascript');res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});
const questions=[
 {id:'q1',subject_id:'s1',unit_id:'u1',stem:'頭蓋内圧亢進でみられる所見はどれか。',instruction:'1つ選べ',choices:[{choice_key:'a',choice_text:'クッシング現象',is_correct:true,explanation:'血圧上昇と徐脈を認める。'},{choice_key:'b',choice_text:'低血圧',is_correct:false,correction_text:'血圧は上昇する。'}],question_occurrences:[{academic_year:'2025',exam_type:'本試',original_question_number:'16',official_answer:'クッシング反応'}]},
 {id:'q2',subject_id:'s2',unit_id:'u2',stem:'小児外科の問題',choices:[{choice_key:'a',choice_text:'別の答え',is_correct:true,explanation:'別の解説'}],question_occurrences:[]}
];
async function run(browser,label,url){
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);
 await page.evaluate(rows=>{window.QBImageLibraryCore={};window.QBImageLibraryStore={};window.qbGetLibrarySubjects=()=>[{id:'s1',name:'脳神経外科学',sort_order:1},{id:'s2',name:'小児外科学',sort_order:2}];window.opened=null;window.qbOpenLibraryQuestion=async value=>{window.opened=value};class Query{constructor(){this.subject=''}select(){return this}eq(key,value){if(key==='subject_id')this.subject=value;return this}in(){return this}order(){return this}range(){return this}then(resolve){resolve({data:this.subject?rows.filter(q=>q.subject_id===this.subject):rows,error:null})}}window.qbSupabase={from:()=>new Query()};const overlay=document.createElement('div');overlay.className='qbLibraryOverlay';overlay.setAttribute('aria-label','ライブラリ');overlay.innerHTML='<section class="qbLibraryPanel"><div class="qbLibraryHeader"><strong>ライブラリ</strong><button>閉じる</button></div><div class="qbLibraryBody"><input aria-label="ファイルを検索"><button>ファイル検索</button></div><div class="qbLibraryFooter">ファイル操作</div></section>';overlay.querySelector('.qbLibraryHeader button').onclick=()=>overlay.remove();document.body.append(overlay)},questions);
 await page.addScriptTag({url:url+'image-library-ui-v1.js'});await page.getByRole('tab',{name:'問題'}).waitFor();
 assert.equal(await page.getByRole('tab',{name:'問題'}).getAttribute('aria-selected'),'true');assert.equal(await page.getByRole('tab',{name:'ファイル'}).getAttribute('aria-selected'),'false');assert.equal(await page.getByLabel('ファイルを検索').isHidden(),true);
 assert.deepEqual(await page.evaluate(q=>['頭蓋内圧','クッシング現象','クッシング反応','血圧上昇'].map(word=>QBQuestionLibrarySearch.matches(q,word)),questions[0]),[['問題文'],['選択肢','解答'],['解答'],['解説']]);
 await page.getByLabel('問題の科目').selectOption('s1');await page.getByLabel('問題を検索').fill('血圧上昇');await page.waitForFunction(()=>document.querySelectorAll('.qbLibraryQuestionCard').length===1);
 const card=page.locator('.qbLibraryQuestionCard');assert.match(await card.textContent(),/解説で一致/);assert.match(await card.textContent(),/脳神経外科学/);await card.click();await page.waitForFunction(()=>window.opened?.questionId==='q1');assert.deepEqual(await page.evaluate(()=>opened),{questionId:'q1',subjectId:'s1',targetUnitId:'u1'});
 assert.deepEqual(errors,[]);await page.close();console.log(label+' PASS default question tab, subject filter, explanation search and direct question navigation');
}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));try{for(const [label,type] of [['Chromium',chromium],['WebKit',webkit]]){const browser=await type.launch();try{await run(browser,label,`http://127.0.0.1:${server.address().port}/`)}finally{await browser.close()}}}finally{server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
