'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {chromium,webkit}=require('playwright'),{boot,edit}=require('./image-library.browser.cjs'),pdf=require('./pdf-fixture.cjs')();
async function run(browser,label){
 const {page:p,errors}=await boot(browser);p.setDefaultTimeout(15000);await p.route(/^blob:/,r=>r.continue());await p.addScriptTag({content:fs.readFileSync(path.resolve(__dirname,'../recent-image-picker-v1.js'),'utf8')});
 await p.locator('.qbLibraryEntry').click();await p.locator('.qbLibraryImageButton').first().waitFor();const input=p.locator('.qbLibraryTools input[type=file][multiple]').first();const files=[{name:'one.png',mimeType:'image/png',buffer:Buffer.from('pixels')},{name:'two.pdf',mimeType:'application/pdf',buffer:pdf}];
 const confirm=async()=>{await p.getByRole('dialog',{name:'追加したファイルを確認',exact:true}).getByRole('button',{name:'確定',exact:true}).click();await p.locator('.qbLibraryUploadReview').waitFor({state:'detached'})};
 await input.setInputFiles(files);await p.getByRole('dialog',{name:'ファイルの追加方法'}).waitFor();assert.equal(await p.evaluate(()=>db.qb_image_library_items.length),2);await p.getByRole('dialog',{name:'ファイルの追加方法'}).getByRole('button',{name:'キャンセル'}).click();assert.equal(await p.evaluate(()=>calls.filter(c=>c[0]==='upload').length),0);
 await input.setInputFiles(files);await p.getByRole('button',{name:'別々のカードに追加（2枚）',exact:true}).click();await confirm();assert.equal(await p.evaluate(()=>db.qb_image_library_items.length),4);assert.equal(await p.evaluate(()=>db.qb_image_library_sets.length),0);assert.match(await p.evaluate(()=>db.qb_image_library_items.at(-1).object_path),/\.pdf$/);
 await input.setInputFiles(files);await p.getByRole('button',{name:'1つのカードにまとめる（2ファイル）',exact:true}).click();await confirm();assert.deepEqual(await p.evaluate(()=>db.qb_image_library_sets.at(-1).image_ids),await p.evaluate(()=>db.qb_image_library_items.slice(-2).map(r=>r.id)));
 // Pasting multiple files goes through the same pre-write choice.
 await p.locator('.qbLibraryOverlay').first().evaluate(n=>{const d=new DataTransfer();d.items.add(new File(['a'],'p1.png',{type:'image/png'}));d.items.add(new File(['b'],'p2.png',{type:'image/png'}));n.dispatchEvent(new ClipboardEvent('paste',{clipboardData:d,bubbles:true,cancelable:true}))});await p.getByRole('button',{name:'別々のカードに追加（2枚）',exact:true}).click();await confirm();assert.equal(await p.evaluate(()=>db.qb_image_library_sets.length),1);
 // Recent files use independent downloads and preserve source attachments.
 await p.evaluate(()=>{db.question_images.push(...['r1','r2'].map((id,i)=>({id,question_id:'q1',image_path:`q1/${id}.png`,placement:'explanation_overview',created_at:`2026-09-${10+i}T00:00:00Z`})));for(const r of db.question_images)objects.set('question-media/'+r.image_path,new Blob(['recent'],{type:'image/png'}));window.originalLinks=JSON.stringify(db.question_images)});
 await p.getByRole('button',{name:'最近のファイル',exact:true}).click();await p.locator('.qbripItem').nth(1).waitFor();await p.locator('.qbripItem').nth(1).click();await p.locator('.qbripItem').nth(0).click();await p.locator('.qbripUse').click();await p.getByRole('button',{name:'1つのカードにまとめる（2ファイル）',exact:true}).click();await confirm();assert.equal(await p.evaluate(()=>db.qb_image_library_sets.length),2);assert.equal(await p.evaluate(()=>JSON.stringify(db.question_images)),await p.evaluate(()=>originalLinks));assert.equal(await p.evaluate(()=>calls.filter(c=>c[1]==='qb_library_record_reading').length),0);
 assert.deepEqual(errors,[]);await p.close();console.log(label+' PASS separate/grouped uploads, PDF MIME, cancellation before writes, paste and recent-file grouping, source preservation');
}
(async()=>{for(const [label,type] of [['Chromium',chromium],['WebKit',webkit]]){const b=await type.launch();try{await run(b,label)}finally{await b.close()}}})().catch(e=>{console.error(e);process.exitCode=1});
