'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium,webkit}=require('playwright');
const root=path.resolve(__dirname,'..');
const pdfFixture=require('./pdf-fixture.cjs');
const fixture=pdfFixture();
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://local').pathname;res.setHeader('Access-Control-Allow-Origin','*');if(pathname==='/fixture.pdf'){res.setHeader('Content-Type','application/pdf');res.end(fixture);return}const file=path.resolve(root,'.'+decodeURIComponent(pathname));if(pathname!=='/'&&!file.startsWith(root+path.sep)){res.writeHead(403).end();return}if(pathname==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head><meta charset="utf-8"></head><body><button id="origin">開く</button><div id="files"></div></body></html>');return}try{res.setHeader('Content-Type',file.endsWith('.mjs')||file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.writeHead(404).end()}});
async function run(browser,label,url){
 const p=await browser.newPage({viewport:{width:1100,height:850}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(25000);await p.goto(url);
 for(const name of ['file-media-v1.css','image-annotation-v1.css'])await p.addStyleTag({url:url+name});
 for(const name of ['file-media-v1.js','image-annotation-model-v1.js','image-annotation-editor-v1.js','pdf-editor-v1.js'])await p.addScriptTag({url:url+name});
 await p.evaluate(async()=>{window.original=await(await fetch('/fixture.pdf')).blob();window.saved=null;QBPDFEditor.open(original,{onSave:async b=>window.saved=b})});
 await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');
 await p.getByRole('button',{name:'このページを編集',exact:true}).click();await p.locator('.qbDrawSave:enabled').waitFor();
 assert.equal(await p.locator('.qbPdfModal').isVisible(),false);assert.equal(await p.getByRole('button',{name:'全体をトリミング',exact:true}).count(),0);
 await p.getByRole('button',{name:'四角い枠',exact:true}).click();const box=await p.locator('.qbDrawCanvas').boundingBox();await p.mouse.move(box.x+box.width*.35,box.y+box.height*.35);await p.mouse.down();await p.mouse.move(box.x+box.width*.6,box.y+box.height*.6,{steps:4});await p.mouse.up();
 await p.getByRole('button',{name:'このページに適用',exact:true}).click();await p.locator('.qbDrawModal').waitFor({state:'detached'});assert.equal(await p.evaluate(()=>saved),null);
 await p.getByRole('button',{name:'次のページ',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent.startsWith('2 / 3'));await p.getByRole('button',{name:'前のページ',exact:true}).click();await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent.startsWith('1 / 3'));
 await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.waitForFunction(()=>saved instanceof Blob);await p.locator('.qbPdfModal').waitFor({state:'detached'});
 const result=await p.evaluate(async()=>{const t=await QBFiles.documentTask(saved),d=await t.promise,attachments=await d.getAttachments(),record=JSON.parse(new TextDecoder().decode(attachments['qb-page-edits-v1.json'].content));const unchanged=await(await fetch(record.original)).text()===await original.text();const page=await d.getPage(1),vp=page.getViewport({scale:1}),c=document.createElement('canvas');c.width=vp.width;c.height=vp.height;await page.render({canvasContext:c.getContext('2d'),viewport:vp}).promise;const pixel=[...c.getContext('2d').getImageData(10,10,1,1).data];await t.destroy();return{type:saved.type,pages:d.numPages,unchanged,items:record.edits[1].editable.scene.items.length,pixel}});
 assert.equal(result.type,'application/pdf');assert.equal(result.pages,3);assert.equal(result.unchanged,true);assert.equal(result.items,1);assert.deepEqual(result.pixel,[255,0,0,255]);
 await p.evaluate(()=>{QBPDFEditor.open(saved,{onSave:async b=>window.saved=b})});await p.waitForFunction(()=>document.querySelector('.qbPdfStatus')?.textContent==='1 / 3ページ');await p.getByRole('button',{name:'このページを編集',exact:true}).click();await p.locator('.qbDrawSave:enabled').waitFor();await p.getByRole('button',{name:'このページに適用',exact:true}).click();await p.locator('.qbDrawModal').waitFor({state:'detached'});await p.getByRole('button',{name:'PDFを保存',exact:true}).click();await p.locator('.qbPdfModal').waitFor({state:'detached'});
 assert.deepEqual(errors,[]);await p.close();console.log(label+' PASS editable multi-page PDF, original retained, transparent overlays, no whole crop, save and reopen');
}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));try{for(const [label,type] of [['Chromium',chromium],['WebKit',webkit]]){const b=await type.launch();try{await run(b,label,`http://127.0.0.1:${server.address().port}/`)}finally{await b.close()}}}finally{server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
